// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.V1.Files.List
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetPurposeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "voice_clone")]
        #pragma warning disable CS1591
        Voice_clone,
        #pragma warning restore CS1591
        [EnumMember(Value = "prompt_audio")]
        #pragma warning disable CS1591
        Prompt_audio,
        #pragma warning restore CS1591
        [EnumMember(Value = "t2a_async_input")]
        #pragma warning disable CS1591
        T2a_async_input,
        #pragma warning restore CS1591
    }
}
