// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using MiniMax.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MiniMax.V1.Files.List
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\files\list
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.V1.Files.List.ListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/files/list?purpose={purpose}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.V1.Files.List.ListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/files/list?purpose={purpose}", rawUrl)
        {
        }
        /// <summary>
        /// List Files
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.ListFileResp"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MiniMax.Models.ListFileResp?> GetAsync(Action<RequestConfiguration<global::MiniMax.V1.Files.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MiniMax.Models.ListFileResp> GetAsync(Action<RequestConfiguration<global::MiniMax.V1.Files.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MiniMax.Models.ListFileResp>(requestInfo, global::MiniMax.Models.ListFileResp.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List Files
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MiniMax.V1.Files.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MiniMax.V1.Files.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.V1.Files.List.ListRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MiniMax.V1.Files.List.ListRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MiniMax.V1.Files.List.ListRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List Files
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListRequestBuilderGetQueryParameters 
        {
            /// <summary>列出文件分类。取值及支持格式如下：1. __voice_clone__: 快速复刻原始文件2. __prompt_audio__: 音色复刻的示例音频3. __t2a_async__: 异步长文本语音生成合成中音频</summary>
            [Obsolete("This property is deprecated, use PurposeAsGetPurposeQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("purpose")]
            public string? Purpose { get; set; }
#nullable restore
#else
            [QueryParameter("purpose")]
            public string Purpose { get; set; }
#endif
            /// <summary>列出文件分类。取值及支持格式如下：1. __voice_clone__: 快速复刻原始文件2. __prompt_audio__: 音色复刻的示例音频3. __t2a_async__: 异步长文本语音生成合成中音频</summary>
            [QueryParameter("purpose")]
            public global::MiniMax.V1.Files.List.GetPurposeQueryParameterType? PurposeAsGetPurposeQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MiniMax.V1.Files.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
