// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MiniMax.V1.Chat;
using MiniMax.V1.Delete_voice;
using MiniMax.V1.Files;
using MiniMax.V1.Get_voice;
using MiniMax.V1.Image_generation;
using MiniMax.V1.Lyrics_generation;
using MiniMax.V1.Music_cover_preprocess;
using MiniMax.V1.Music_generation;
using MiniMax.V1.Query;
using MiniMax.V1.T2a_async_v2;
using MiniMax.V1.T2a_v2;
using MiniMax.V1.Video_generation;
using MiniMax.V1.Voice_clone;
using MiniMax.V1.Voice_design;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MiniMax.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The chat property</summary>
        public global::MiniMax.V1.Chat.ChatRequestBuilder Chat
        {
            get => new global::MiniMax.V1.Chat.ChatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The delete_voice property</summary>
        public global::MiniMax.V1.Delete_voice.Delete_voiceRequestBuilder Delete_voice
        {
            get => new global::MiniMax.V1.Delete_voice.Delete_voiceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public global::MiniMax.V1.Files.FilesRequestBuilder Files
        {
            get => new global::MiniMax.V1.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_voice property</summary>
        public global::MiniMax.V1.Get_voice.Get_voiceRequestBuilder Get_voice
        {
            get => new global::MiniMax.V1.Get_voice.Get_voiceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The image_generation property</summary>
        public global::MiniMax.V1.Image_generation.Image_generationRequestBuilder Image_generation
        {
            get => new global::MiniMax.V1.Image_generation.Image_generationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lyrics_generation property</summary>
        public global::MiniMax.V1.Lyrics_generation.Lyrics_generationRequestBuilder Lyrics_generation
        {
            get => new global::MiniMax.V1.Lyrics_generation.Lyrics_generationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The music_cover_preprocess property</summary>
        public global::MiniMax.V1.Music_cover_preprocess.Music_cover_preprocessRequestBuilder Music_cover_preprocess
        {
            get => new global::MiniMax.V1.Music_cover_preprocess.Music_cover_preprocessRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The music_generation property</summary>
        public global::MiniMax.V1.Music_generation.Music_generationRequestBuilder Music_generation
        {
            get => new global::MiniMax.V1.Music_generation.Music_generationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The query property</summary>
        public global::MiniMax.V1.Query.QueryRequestBuilder Query
        {
            get => new global::MiniMax.V1.Query.QueryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The t2a_async_v2 property</summary>
        public global::MiniMax.V1.T2a_async_v2.T2a_async_v2RequestBuilder T2a_async_v2
        {
            get => new global::MiniMax.V1.T2a_async_v2.T2a_async_v2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The t2a_v2 property</summary>
        public global::MiniMax.V1.T2a_v2.T2a_v2RequestBuilder T2a_v2
        {
            get => new global::MiniMax.V1.T2a_v2.T2a_v2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The video_generation property</summary>
        public global::MiniMax.V1.Video_generation.Video_generationRequestBuilder Video_generation
        {
            get => new global::MiniMax.V1.Video_generation.Video_generationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The voice_clone property</summary>
        public global::MiniMax.V1.Voice_clone.Voice_cloneRequestBuilder Voice_clone
        {
            get => new global::MiniMax.V1.Voice_clone.Voice_cloneRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The voice_design property</summary>
        public global::MiniMax.V1.Voice_design.Voice_designRequestBuilder Voice_design
        {
            get => new global::MiniMax.V1.Voice_design.Voice_designRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
