// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.V1.Files.Upload
{
    /// <summary>文件使用目的。取值及支持格式如下：- __prompt_audio__: 快速复刻原始文件，（支持mp3、m4a、wav格式）</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UploadPostRequestBody
    {
        [EnumMember(Value = "prompt_audio")]
        #pragma warning disable CS1591
        Prompt_audio,
        #pragma warning restore CS1591
    }
}
