// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using MiniMax.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MiniMax.V1.Query.Video_generation
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\query\video_generation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Video_generationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.V1.Query.Video_generation.Video_generationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Video_generationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/query/video_generation?task_id={task_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.V1.Query.Video_generation.Video_generationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Video_generationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/query/video_generation?task_id={task_id}", rawUrl)
        {
        }
        /// <summary>
        /// Query Video Generation Task
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.QueryVideoGenerationTaskResp"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MiniMax.Models.QueryVideoGenerationTaskResp?> GetAsync(Action<RequestConfiguration<global::MiniMax.V1.Query.Video_generation.Video_generationRequestBuilder.Video_generationRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MiniMax.Models.QueryVideoGenerationTaskResp> GetAsync(Action<RequestConfiguration<global::MiniMax.V1.Query.Video_generation.Video_generationRequestBuilder.Video_generationRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MiniMax.Models.QueryVideoGenerationTaskResp>(requestInfo, global::MiniMax.Models.QueryVideoGenerationTaskResp.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Query Video Generation Task
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MiniMax.V1.Query.Video_generation.Video_generationRequestBuilder.Video_generationRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MiniMax.V1.Query.Video_generation.Video_generationRequestBuilder.Video_generationRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.V1.Query.Video_generation.Video_generationRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MiniMax.V1.Query.Video_generation.Video_generationRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MiniMax.V1.Query.Video_generation.Video_generationRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Query Video Generation Task
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Video_generationRequestBuilderGetQueryParameters 
        {
            /// <summary>待查询的任务 ID。只能查询当前账号创建的任务</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("task_id")]
            public string? TaskId { get; set; }
#nullable restore
#else
            [QueryParameter("task_id")]
            public string TaskId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Video_generationRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MiniMax.V1.Query.Video_generation.Video_generationRequestBuilder.Video_generationRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
