// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MiniMax.V1.Files.Delete;
using MiniMax.V1.Files.List;
using MiniMax.V1.Files.Retrieve;
using MiniMax.V1.Files.Retrieve_content;
using MiniMax.V1.Files.Upload;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MiniMax.V1.Files
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\files
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The deletePath property</summary>
        public global::MiniMax.V1.Files.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::MiniMax.V1.Files.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public global::MiniMax.V1.Files.List.ListRequestBuilder List
        {
            get => new global::MiniMax.V1.Files.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The retrieve property</summary>
        public global::MiniMax.V1.Files.Retrieve.RetrieveRequestBuilder Retrieve
        {
            get => new global::MiniMax.V1.Files.Retrieve.RetrieveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The retrieve_content property</summary>
        public global::MiniMax.V1.Files.Retrieve_content.Retrieve_contentRequestBuilder Retrieve_content
        {
            get => new global::MiniMax.V1.Files.Retrieve_content.Retrieve_contentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload property</summary>
        public global::MiniMax.V1.Files.Upload.UploadRequestBuilder Upload
        {
            get => new global::MiniMax.V1.Files.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.V1.Files.FilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/files", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.V1.Files.FilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/files", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
