// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MiniMax.V1.Query.T2a_async_query_v2;
using MiniMax.V1.Query.Video_generation;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MiniMax.V1.Query
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\query
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QueryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The t2a_async_query_v2 property</summary>
        public global::MiniMax.V1.Query.T2a_async_query_v2.T2a_async_query_v2RequestBuilder T2a_async_query_v2
        {
            get => new global::MiniMax.V1.Query.T2a_async_query_v2.T2a_async_query_v2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The video_generation property</summary>
        public global::MiniMax.V1.Query.Video_generation.Video_generationRequestBuilder Video_generation
        {
            get => new global::MiniMax.V1.Query.Video_generation.Video_generationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.V1.Query.QueryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/query", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.V1.Query.QueryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/query", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
