// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using MiniMax.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MiniMax.V1.Query.T2a_async_query_v2
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\query\t2a_async_query_v2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class T2a_async_query_v2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.V1.Query.T2a_async_query_v2.T2a_async_query_v2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public T2a_async_query_v2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/query/t2a_async_query_v2?task_id={task_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.V1.Query.T2a_async_query_v2.T2a_async_query_v2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public T2a_async_query_v2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/query/t2a_async_query_v2?task_id={task_id}", rawUrl)
        {
        }
        /// <summary>
        /// Query T2A Async V2 Task Status
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.T2AAsyncV2QueryResp"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MiniMax.Models.T2AAsyncV2QueryResp?> GetAsync(Action<RequestConfiguration<global::MiniMax.V1.Query.T2a_async_query_v2.T2a_async_query_v2RequestBuilder.T2a_async_query_v2RequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MiniMax.Models.T2AAsyncV2QueryResp> GetAsync(Action<RequestConfiguration<global::MiniMax.V1.Query.T2a_async_query_v2.T2a_async_query_v2RequestBuilder.T2a_async_query_v2RequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MiniMax.Models.T2AAsyncV2QueryResp>(requestInfo, global::MiniMax.Models.T2AAsyncV2QueryResp.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Query T2A Async V2 Task Status
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MiniMax.V1.Query.T2a_async_query_v2.T2a_async_query_v2RequestBuilder.T2a_async_query_v2RequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MiniMax.V1.Query.T2a_async_query_v2.T2a_async_query_v2RequestBuilder.T2a_async_query_v2RequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.V1.Query.T2a_async_query_v2.T2a_async_query_v2RequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MiniMax.V1.Query.T2a_async_query_v2.T2a_async_query_v2RequestBuilder WithUrl(string rawUrl)
        {
            return new global::MiniMax.V1.Query.T2a_async_query_v2.T2a_async_query_v2RequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Query T2A Async V2 Task Status
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class T2a_async_query_v2RequestBuilderGetQueryParameters 
        {
            /// <summary>任务 ID，提交任务时返回的信息</summary>
            [QueryParameter("task_id")]
            public long? TaskId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class T2a_async_query_v2RequestBuilderGetRequestConfiguration : RequestConfiguration<global::MiniMax.V1.Query.T2a_async_query_v2.T2a_async_query_v2RequestBuilder.T2a_async_query_v2RequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
