// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>音频编码格式。</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AudioSetting_format
    {
        [EnumMember(Value = "mp3")]
        #pragma warning disable CS1591
        Mp3,
        #pragma warning restore CS1591
        [EnumMember(Value = "wav")]
        #pragma warning disable CS1591
        Wav,
        #pragma warning restore CS1591
        [EnumMember(Value = "pcm")]
        #pragma warning disable CS1591
        Pcm,
        #pragma warning restore CS1591
    }
}
