// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    /// <summary>
    /// 音频输出配置
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AudioSetting : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>比特率。可选值：`32000`, `64000`, `128000`, `256000`</summary>
        public int? Bitrate { get; set; }
        /// <summary>音频编码格式。</summary>
        public global::MiniMax.Models.AudioSetting_format? Format { get; set; }
        /// <summary>采样率。可选值：`16000`, `24000`, `32000`, `44100`</summary>
        public int? SampleRate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.AudioSetting"/> and sets the default values.
        /// </summary>
        public AudioSetting()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.AudioSetting"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.AudioSetting CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.AudioSetting();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bitrate", n => { Bitrate = n.GetIntValue(); } },
                { "format", n => { Format = n.GetEnumValue<global::MiniMax.Models.AudioSetting_format>(); } },
                { "sample_rate", n => { SampleRate = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("bitrate", Bitrate);
            writer.WriteEnumValue<global::MiniMax.Models.AudioSetting_format>("format", Format);
            writer.WriteIntValue("sample_rate", SampleRate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
