// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>生成停止的原因：`stop` (自然结束), `length` (达到 `max_completion_tokens` 上限)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatCompletionResp_choices_finish_reason
    {
        [EnumMember(Value = "stop")]
        #pragma warning disable CS1591
        Stop,
        #pragma warning restore CS1591
        [EnumMember(Value = "length")]
        #pragma warning disable CS1591
        Length,
        #pragma warning restore CS1591
    }
}
