// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChatCompletionResp_choices : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>生成停止的原因：`stop` (自然结束), `length` (达到 `max_completion_tokens` 上限)</summary>
        public global::MiniMax.Models.ChatCompletionResp_choices_finish_reason? FinishReason { get; set; }
        /// <summary>选项的索引，从 0 开始</summary>
        public int? Index { get; set; }
        /// <summary>模型生成的完整回复</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.ChatCompletionResp_choices_message? Message { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.ChatCompletionResp_choices_message Message { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.ChatCompletionResp_choices"/> and sets the default values.
        /// </summary>
        public ChatCompletionResp_choices()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.ChatCompletionResp_choices"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.ChatCompletionResp_choices CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.ChatCompletionResp_choices();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "finish_reason", n => { FinishReason = n.GetEnumValue<global::MiniMax.Models.ChatCompletionResp_choices_finish_reason>(); } },
                { "index", n => { Index = n.GetIntValue(); } },
                { "message", n => { Message = n.GetObjectValue<global::MiniMax.Models.ChatCompletionResp_choices_message>(global::MiniMax.Models.ChatCompletionResp_choices_message.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::MiniMax.Models.ChatCompletionResp_choices_finish_reason>("finish_reason", FinishReason);
            writer.WriteIntValue("index", Index);
            writer.WriteObjectValue<global::MiniMax.Models.ChatCompletionResp_choices_message>("message", Message);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
