// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>对象类型。非流式为 `chat.completion`，流式为 `chat.completion.chunk`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatCompletionResp_object
    {
        [EnumMember(Value = "chat.completion")]
        #pragma warning disable CS1591
        ChatCompletion,
        #pragma warning restore CS1591
        [EnumMember(Value = "chat.completion.chunk")]
        #pragma warning disable CS1591
        ChatCompletionChunk,
        #pragma warning restore CS1591
    }
}
