// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>角色，固定为 `assistant`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatCompletionResp_choices_message_role
    {
        [EnumMember(Value = "assistant")]
        #pragma warning disable CS1591
        Assistant,
        #pragma warning restore CS1591
    }
}
