// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChatCompletionResp : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>错误状态码和详情</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.ChatCompletionResp_base_resp? BaseResp { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.ChatCompletionResp_base_resp BaseResp { get; set; }
#endif
        /// <summary>响应选择列表</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MiniMax.Models.ChatCompletionResp_choices>? Choices { get; set; }
#nullable restore
#else
        public List<global::MiniMax.Models.ChatCompletionResp_choices> Choices { get; set; }
#endif
        /// <summary>响应创建的 Unix 时间戳（秒）</summary>
        public long? Created { get; set; }
        /// <summary>本次响应的唯一 ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>输入内容是否命中敏感词。如果输入内容严重违规，接口会返回内容违规错误信息，回复内容为空</summary>
        public bool? InputSensitive { get; set; }
        /// <summary>输入命中敏感词类型，当input_sensitive为true时返回。取值为以下其一：1 严重违规；2 色情；3 广告；4 违禁；5 谩骂；6 暴恐；7 其他</summary>
        public long? InputSensitiveType { get; set; }
        /// <summary>本次请求使用的模型 ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>对象类型。非流式为 `chat.completion`，流式为 `chat.completion.chunk`</summary>
        public global::MiniMax.Models.ChatCompletionResp_object? Object { get; set; }
        /// <summary>输出内容是否命中敏感词。如果输出内容严重违规，接口会返回内容违规错误信息，回复内容为空</summary>
        public bool? OutputSensitive { get; set; }
        /// <summary>输出命中敏感词类型</summary>
        public long? OutputSensitiveType { get; set; }
        /// <summary>本次请求的 Token 使用情况</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.Usage? Usage { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.Usage Usage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.ChatCompletionResp"/> and sets the default values.
        /// </summary>
        public ChatCompletionResp()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.ChatCompletionResp"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.ChatCompletionResp CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.ChatCompletionResp();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base_resp", n => { BaseResp = n.GetObjectValue<global::MiniMax.Models.ChatCompletionResp_base_resp>(global::MiniMax.Models.ChatCompletionResp_base_resp.CreateFromDiscriminatorValue); } },
                { "choices", n => { Choices = n.GetCollectionOfObjectValues<global::MiniMax.Models.ChatCompletionResp_choices>(global::MiniMax.Models.ChatCompletionResp_choices.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created", n => { Created = n.GetLongValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "input_sensitive", n => { InputSensitive = n.GetBoolValue(); } },
                { "input_sensitive_type", n => { InputSensitiveType = n.GetLongValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::MiniMax.Models.ChatCompletionResp_object>(); } },
                { "output_sensitive", n => { OutputSensitive = n.GetBoolValue(); } },
                { "output_sensitive_type", n => { OutputSensitiveType = n.GetLongValue(); } },
                { "usage", n => { Usage = n.GetObjectValue<global::MiniMax.Models.Usage>(global::MiniMax.Models.Usage.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MiniMax.Models.ChatCompletionResp_base_resp>("base_resp", BaseResp);
            writer.WriteCollectionOfObjectValues<global::MiniMax.Models.ChatCompletionResp_choices>("choices", Choices);
            writer.WriteLongValue("created", Created);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("input_sensitive", InputSensitive);
            writer.WriteLongValue("input_sensitive_type", InputSensitiveType);
            writer.WriteStringValue("model", Model);
            writer.WriteEnumValue<global::MiniMax.Models.ChatCompletionResp_object>("object", Object);
            writer.WriteBoolValue("output_sensitive", OutputSensitive);
            writer.WriteLongValue("output_sensitive_type", OutputSensitiveType);
            writer.WriteObjectValue<global::MiniMax.Models.Usage>("usage", Usage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
