// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>模型 ID</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatCompletionReq_model
    {
        [EnumMember(Value = "MiniMax-M2.7")]
        #pragma warning disable CS1591
        MiniMaxM27,
        #pragma warning restore CS1591
        [EnumMember(Value = "MiniMax-M2.7-highspeed")]
        #pragma warning disable CS1591
        MiniMaxM27Highspeed,
        #pragma warning restore CS1591
        [EnumMember(Value = "MiniMax-M2.5")]
        #pragma warning disable CS1591
        MiniMaxM25,
        #pragma warning restore CS1591
        [EnumMember(Value = "MiniMax-M2.1")]
        #pragma warning disable CS1591
        MiniMaxM21,
        #pragma warning restore CS1591
    }
}
