// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChatCompletionReq : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>指定生成内容长度的上限（Token 数），上限为 2048。超过上限的内容会被截断。如果生成因 `length` 原因中断，请尝试调高此值</summary>
        public long? MaxCompletionTokens { get; set; }
        /// <summary>包含对话历史的消息列表。更多 message 参数说明请参考 [文本对话使用指南](/guides/text-chat)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MiniMax.Models.Message>? Messages { get; set; }
#nullable restore
#else
        public List<global::MiniMax.Models.Message> Messages { get; set; }
#endif
        /// <summary>模型 ID</summary>
        public global::MiniMax.Models.ChatCompletionReq_model? Model { get; set; }
        /// <summary>是否使用流式传输，默认为 `false`。设置为 `true` 后，响应将分批返回</summary>
        public bool? Stream { get; set; }
        /// <summary>温度系数，影响输出随机性，取值范围 (0, 1]，模型默认值为 1.0。值越高，输出越随机；值越低，输出越确定</summary>
        public double? Temperature { get; set; }
        /// <summary>采样策略，影响输出随机性，取值范围 (0, 1]，模型默认值为 0.95</summary>
        public double? TopP { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.ChatCompletionReq"/> and sets the default values.
        /// </summary>
        public ChatCompletionReq()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.ChatCompletionReq"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.ChatCompletionReq CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.ChatCompletionReq();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "max_completion_tokens", n => { MaxCompletionTokens = n.GetLongValue(); } },
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::MiniMax.Models.Message>(global::MiniMax.Models.Message.CreateFromDiscriminatorValue)?.AsList(); } },
                { "model", n => { Model = n.GetEnumValue<global::MiniMax.Models.ChatCompletionReq_model>(); } },
                { "stream", n => { Stream = n.GetBoolValue(); } },
                { "temperature", n => { Temperature = n.GetDoubleValue(); } },
                { "top_p", n => { TopP = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("max_completion_tokens", MaxCompletionTokens);
            writer.WriteCollectionOfObjectValues<global::MiniMax.Models.Message>("messages", Messages);
            writer.WriteEnumValue<global::MiniMax.Models.ChatCompletionReq_model>("model", Model);
            writer.WriteBoolValue("stream", Stream);
            writer.WriteDoubleValue("temperature", Temperature);
            writer.WriteDoubleValue("top_p", TopP);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
