// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>内容块类型：- `text`: 文本内容- `thinking`: 模型思考过程</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ContentBlock_type
    {
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "thinking")]
        #pragma warning disable CS1591
        Thinking,
        #pragma warning restore CS1591
    }
}
