// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>模型名称。必须为 `music-cover`。</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CoverPreprocessReq_model
    {
        [EnumMember(Value = "music-cover")]
        #pragma warning disable CS1591
        MusicCover,
        #pragma warning restore CS1591
    }
}
