// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CoverPreprocessReq : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Base64 编码的参考音频。`audio_url` 和 `audio_base64` 必须且只能提供其中一个。参考音频要求：- 时长：6 秒至 6 分钟- 大小：最大 50 MB- 格式：支持常见音频格式（mp3、wav、flac 等）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AudioBase64 { get; set; }
#nullable restore
#else
        public string AudioBase64 { get; set; }
#endif
        /// <summary>参考音频的 URL 地址。`audio_url` 和 `audio_base64` 必须且只能提供其中一个。参考音频要求：- 时长：6 秒至 6 分钟- 大小：最大 50 MB- 格式：支持常见音频格式（mp3、wav、flac 等）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AudioUrl { get; set; }
#nullable restore
#else
        public string AudioUrl { get; set; }
#endif
        /// <summary>模型名称。必须为 `music-cover`。</summary>
        public global::MiniMax.Models.CoverPreprocessReq_model? Model { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.CoverPreprocessReq"/> and sets the default values.
        /// </summary>
        public CoverPreprocessReq()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.CoverPreprocessReq"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.CoverPreprocessReq CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.CoverPreprocessReq();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audio_base64", n => { AudioBase64 = n.GetStringValue(); } },
                { "audio_url", n => { AudioUrl = n.GetStringValue(); } },
                { "model", n => { Model = n.GetEnumValue<global::MiniMax.Models.CoverPreprocessReq_model>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("audio_base64", AudioBase64);
            writer.WriteStringValue("audio_url", AudioUrl);
            writer.WriteEnumValue<global::MiniMax.Models.CoverPreprocessReq_model>("model", Model);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
