// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CoverPreprocessResp : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>参考音频的时长（秒）。</summary>
        public double? AudioDuration { get; set; }
        /// <summary>状态码及详情</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.BaseResp? BaseResp { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.BaseResp BaseResp { get; set; }
#endif
        /// <summary>预处理后的音频特征唯一标识，有效期 24 小时。将此 ID 传入[音乐生成接口](/api-reference/music-generation)的 `cover_feature_id` 参数以进行两步翻唱。相同音频内容会返回相同的 `cover_feature_id`（基于 MD5 去重）。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CoverFeatureId { get; set; }
#nullable restore
#else
        public string CoverFeatureId { get; set; }
#endif
        /// <summary>通过 ASR 从参考音频中提取并格式化的歌词，包含 `[Verse]`、`[Chorus]`、`[Bridge]` 等段落标签。你可以修改这些歌词后传入音乐生成接口。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FormattedLyrics { get; set; }
#nullable restore
#else
        public string FormattedLyrics { get; set; }
#endif
        /// <summary>JSON 字符串，包含歌曲结构分析结果，含段落类型（`intro`、`verse`、`chorus`、`bridge`、`outro`、`inst`、`silence`）及其起止时间戳（秒）。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StructureResult { get; set; }
#nullable restore
#else
        public string StructureResult { get; set; }
#endif
        /// <summary>请求追踪 ID。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TraceId { get; set; }
#nullable restore
#else
        public string TraceId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.CoverPreprocessResp"/> and sets the default values.
        /// </summary>
        public CoverPreprocessResp()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.CoverPreprocessResp"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.CoverPreprocessResp CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.CoverPreprocessResp();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audio_duration", n => { AudioDuration = n.GetDoubleValue(); } },
                { "base_resp", n => { BaseResp = n.GetObjectValue<global::MiniMax.Models.BaseResp>(global::MiniMax.Models.BaseResp.CreateFromDiscriminatorValue); } },
                { "cover_feature_id", n => { CoverFeatureId = n.GetStringValue(); } },
                { "formatted_lyrics", n => { FormattedLyrics = n.GetStringValue(); } },
                { "structure_result", n => { StructureResult = n.GetStringValue(); } },
                { "trace_id", n => { TraceId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("audio_duration", AudioDuration);
            writer.WriteObjectValue<global::MiniMax.Models.BaseResp>("base_resp", BaseResp);
            writer.WriteStringValue("cover_feature_id", CoverFeatureId);
            writer.WriteStringValue("formatted_lyrics", FormattedLyrics);
            writer.WriteStringValue("structure_result", StructureResult);
            writer.WriteStringValue("trace_id", TraceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
