// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateMessageReq : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>指定生成内容长度的上限（Token 数），上限为 2048。超过上限的内容会被截断。如果生成因 `length` 原因中断，请尝试调高此值</summary>
        public long? MaxTokens { get; set; }
        /// <summary>包含对话历史的消息列表</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MiniMax.Models.Message>? Messages { get; set; }
#nullable restore
#else
        public List<global::MiniMax.Models.Message> Messages { get; set; }
#endif
        /// <summary>模型 ID</summary>
        public global::MiniMax.Models.CreateMessageReq_model? Model { get; set; }
        /// <summary>是否使用流式传输，默认为 `false`。设置为 `true` 后，响应将分批返回</summary>
        public bool? Stream { get; set; }
        /// <summary>设定模型的角色和行为</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.CreateMessageReq.CreateMessageReq_system? System { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.CreateMessageReq.CreateMessageReq_system System { get; set; }
#endif
        /// <summary>温度系数，影响输出随机性，取值范围 (0, 1]，`MiniMax-M2.7` 模型默认值为 1.0。值越高，输出越随机；值越低，输出越确定</summary>
        public double? Temperature { get; set; }
        /// <summary>采样策略，影响输出随机性，取值范围 (0, 1]，`MiniMax-M2.7` 模型默认值为 0.95</summary>
        public double? TopP { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.CreateMessageReq"/> and sets the default values.
        /// </summary>
        public CreateMessageReq()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.CreateMessageReq"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.CreateMessageReq CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.CreateMessageReq();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "max_tokens", n => { MaxTokens = n.GetLongValue(); } },
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::MiniMax.Models.Message>(global::MiniMax.Models.Message.CreateFromDiscriminatorValue)?.AsList(); } },
                { "model", n => { Model = n.GetEnumValue<global::MiniMax.Models.CreateMessageReq_model>(); } },
                { "stream", n => { Stream = n.GetBoolValue(); } },
                { "system", n => { System = n.GetObjectValue<global::MiniMax.Models.CreateMessageReq.CreateMessageReq_system>(global::MiniMax.Models.CreateMessageReq.CreateMessageReq_system.CreateFromDiscriminatorValue); } },
                { "temperature", n => { Temperature = n.GetDoubleValue(); } },
                { "top_p", n => { TopP = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("max_tokens", MaxTokens);
            writer.WriteCollectionOfObjectValues<global::MiniMax.Models.Message>("messages", Messages);
            writer.WriteEnumValue<global::MiniMax.Models.CreateMessageReq_model>("model", Model);
            writer.WriteBoolValue("stream", Stream);
            writer.WriteObjectValue<global::MiniMax.Models.CreateMessageReq.CreateMessageReq_system>("system", System);
            writer.WriteDoubleValue("temperature", Temperature);
            writer.WriteDoubleValue("top_p", TopP);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="string"/>, List&lt;global::MiniMax.Models.CreateMessageReq_systemMember1&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CreateMessageReq_system : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type List&lt;global::MiniMax.Models.CreateMessageReq_systemMember1&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<global::MiniMax.Models.CreateMessageReq_systemMember1>? CreateMessageReqSystemMember1 { get; set; }
#nullable restore
#else
            public List<global::MiniMax.Models.CreateMessageReq_systemMember1> CreateMessageReqSystemMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MiniMax.Models.CreateMessageReq.CreateMessageReq_system"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MiniMax.Models.CreateMessageReq.CreateMessageReq_system CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::MiniMax.Models.CreateMessageReq.CreateMessageReq_system();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else if(parseNode.GetCollectionOfObjectValues<global::MiniMax.Models.CreateMessageReq_systemMember1>(global::MiniMax.Models.CreateMessageReq_systemMember1.CreateFromDiscriminatorValue)?.AsList() is List<global::MiniMax.Models.CreateMessageReq_systemMember1> createMessageReqSystemMember1Value)
                {
                    result.CreateMessageReqSystemMember1 = createMessageReqSystemMember1Value;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else if(CreateMessageReqSystemMember1 != null)
                {
                    writer.WriteCollectionOfObjectValues<global::MiniMax.Models.CreateMessageReq_systemMember1>(null, CreateMessageReqSystemMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
