// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>生成停止的原因：- `end_turn`: 模型自然结束- `max_tokens`: 达到 `max_tokens` 上限- `stop_sequence`: 命中停止序列</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateMessageResp_stop_reason
    {
        [EnumMember(Value = "end_turn")]
        #pragma warning disable CS1591
        End_turn,
        #pragma warning restore CS1591
        [EnumMember(Value = "max_tokens")]
        #pragma warning disable CS1591
        Max_tokens,
        #pragma warning restore CS1591
        [EnumMember(Value = "stop_sequence")]
        #pragma warning disable CS1591
        Stop_sequence,
        #pragma warning restore CS1591
    }
}
