// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateMessageResp : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>错误状态码和详情</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.CreateMessageResp_base_resp? BaseResp { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.CreateMessageResp_base_resp BaseResp { get; set; }
#endif
        /// <summary>响应内容块列表</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MiniMax.Models.ContentBlock>? Content { get; set; }
#nullable restore
#else
        public List<global::MiniMax.Models.ContentBlock> Content { get; set; }
#endif
        /// <summary>本次响应的唯一 ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>本次请求使用的模型 ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>角色，固定为 `assistant`</summary>
        public global::MiniMax.Models.CreateMessageResp_role? Role { get; set; }
        /// <summary>生成停止的原因：- `end_turn`: 模型自然结束- `max_tokens`: 达到 `max_tokens` 上限- `stop_sequence`: 命中停止序列</summary>
        public global::MiniMax.Models.CreateMessageResp_stop_reason? StopReason { get; set; }
        /// <summary>对象类型，固定为 `message`</summary>
        public global::MiniMax.Models.CreateMessageResp_type? Type { get; set; }
        /// <summary>本次请求的 Token 使用情况</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.Usage? Usage { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.Usage Usage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.CreateMessageResp"/> and sets the default values.
        /// </summary>
        public CreateMessageResp()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.CreateMessageResp"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.CreateMessageResp CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.CreateMessageResp();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base_resp", n => { BaseResp = n.GetObjectValue<global::MiniMax.Models.CreateMessageResp_base_resp>(global::MiniMax.Models.CreateMessageResp_base_resp.CreateFromDiscriminatorValue); } },
                { "content", n => { Content = n.GetCollectionOfObjectValues<global::MiniMax.Models.ContentBlock>(global::MiniMax.Models.ContentBlock.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "role", n => { Role = n.GetEnumValue<global::MiniMax.Models.CreateMessageResp_role>(); } },
                { "stop_reason", n => { StopReason = n.GetEnumValue<global::MiniMax.Models.CreateMessageResp_stop_reason>(); } },
                { "type", n => { Type = n.GetEnumValue<global::MiniMax.Models.CreateMessageResp_type>(); } },
                { "usage", n => { Usage = n.GetObjectValue<global::MiniMax.Models.Usage>(global::MiniMax.Models.Usage.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MiniMax.Models.CreateMessageResp_base_resp>("base_resp", BaseResp);
            writer.WriteCollectionOfObjectValues<global::MiniMax.Models.ContentBlock>("content", Content);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("model", Model);
            writer.WriteEnumValue<global::MiniMax.Models.CreateMessageResp_role>("role", Role);
            writer.WriteEnumValue<global::MiniMax.Models.CreateMessageResp_stop_reason>("stop_reason", StopReason);
            writer.WriteEnumValue<global::MiniMax.Models.CreateMessageResp_type>("type", Type);
            writer.WriteObjectValue<global::MiniMax.Models.Usage>("usage", Usage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
