// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>对象类型，固定为 `message`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateMessageResp_type
    {
        [EnumMember(Value = "message")]
        #pragma warning disable CS1591
        Message,
        #pragma warning restore CS1591
    }
}
