// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>取值范围：`voice_cloning`（克隆的音色）/`voice_generation`（基于文本提示生成的音色），注意仅支持删除这两种类别的音色</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeleteVoiceReq_voice_type
    {
        [EnumMember(Value = "voice_cloning")]
        #pragma warning disable CS1591
        Voice_cloning,
        #pragma warning restore CS1591
        [EnumMember(Value = "voice_generation")]
        #pragma warning disable CS1591
        Voice_generation,
        #pragma warning restore CS1591
    }
}
