// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>文件使用目的。取值及支持格式如下：1. voice_clone2. prompt_audio3. t2a_async4. t2a_async_input5. video_generation</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeleteFileReq_purpose
    {
        [EnumMember(Value = "voice_clone")]
        #pragma warning disable CS1591
        Voice_clone,
        #pragma warning restore CS1591
        [EnumMember(Value = "prompt_audio")]
        #pragma warning disable CS1591
        Prompt_audio,
        #pragma warning restore CS1591
        [EnumMember(Value = "t2a_async")]
        #pragma warning disable CS1591
        T2a_async,
        #pragma warning restore CS1591
        [EnumMember(Value = "t2a_async_input")]
        #pragma warning disable CS1591
        T2a_async_input,
        #pragma warning restore CS1591
        [EnumMember(Value = "video_generation")]
        #pragma warning disable CS1591
        Video_generation,
        #pragma warning restore CS1591
    }
}
