// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DeleteVoiceReq : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>希望删除音色的 voice_id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VoiceId { get; set; }
#nullable restore
#else
        public string VoiceId { get; set; }
#endif
        /// <summary>取值范围：`voice_cloning`（克隆的音色）/`voice_generation`（基于文本提示生成的音色），注意仅支持删除这两种类别的音色</summary>
        public global::MiniMax.Models.DeleteVoiceReq_voice_type? VoiceType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.DeleteVoiceReq"/> and sets the default values.
        /// </summary>
        public DeleteVoiceReq()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.DeleteVoiceReq"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.DeleteVoiceReq CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.DeleteVoiceReq();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "voice_id", n => { VoiceId = n.GetStringValue(); } },
                { "voice_type", n => { VoiceType = n.GetEnumValue<global::MiniMax.Models.DeleteVoiceReq_voice_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("voice_id", VoiceId);
            writer.WriteEnumValue<global::MiniMax.Models.DeleteVoiceReq_voice_type>("voice_type", VoiceType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
