// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>使用的模型名称。可选值：- `music-2.6`（推荐）：文本生成音乐，仅限 Token Plan 用户和付费用户使用，RPM 较高- `music-cover`：基于参考音频生成翻唱版本，仅限 Token Plan 用户和付费用户使用，RPM 较高- `music-2.6-free`：`music-2.6` 的限免版本，所有用户可通过 API Key 使用，RPM 较低- `music-cover-free`：`music-cover` 的限免版本，所有用户可通过 API Key 使用，RPM 较低</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GenerateMusicReq_model
    {
        [EnumMember(Value = "music-2.6")]
        #pragma warning disable CS1591
        Music26,
        #pragma warning restore CS1591
        [EnumMember(Value = "music-cover")]
        #pragma warning disable CS1591
        MusicCover,
        #pragma warning restore CS1591
        [EnumMember(Value = "music-2.6-free")]
        #pragma warning disable CS1591
        Music26Free,
        #pragma warning restore CS1591
        [EnumMember(Value = "music-cover-free")]
        #pragma warning disable CS1591
        MusicCoverFree,
        #pragma warning restore CS1591
    }
}
