// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GenerateMusicReq : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>是否在音频末尾添加水印，默认为 `false`。仅在非流式 (`stream: false`) 请求时生效</summary>
        public bool? AigcWatermark { get; set; }
        /// <summary>Base64 编码的参考音频。仅用于 `music-cover` / `music-cover-free` 模型。`audio_url` 和 `audio_base64` 必须且只能提供其中一个。与 `cover_feature_id` 互斥。参考音频要求：- 时长：6 秒至 6 分钟- 大小：最大 50 MB- 格式：支持常见音频格式（mp3、wav、flac 等）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AudioBase64 { get; set; }
#nullable restore
#else
        public string AudioBase64 { get; set; }
#endif
        /// <summary>音频输出配置</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.AudioSetting? AudioSetting { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.AudioSetting AudioSetting { get; set; }
#endif
        /// <summary>参考音频的 URL 地址。仅用于 `music-cover` / `music-cover-free` 模型。`audio_url` 和 `audio_base64` 必须且只能提供其中一个。与 `cover_feature_id` 互斥。参考音频要求：- 时长：6 秒至 6 分钟- 大小：最大 50 MB- 格式：支持常见音频格式（mp3、wav、flac 等）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AudioUrl { get; set; }
#nullable restore
#else
        public string AudioUrl { get; set; }
#endif
        /// <summary>[翻唱前处理](/api-reference/music-cover-preprocess) 接口返回的特征 ID，用于**两步翻唱流程**，支持修改歌词后生成翻唱。仅用于 `music-cover` / `music-cover-free` 模型。与 `audio_url` 和 `audio_base64` 互斥。- 传入时 `lyrics` 为必填（长度限制 [10, 1000] 个字符）- `cover_feature_id` 有效期为 24 小时- 相同音频内容返回相同的 `cover_feature_id`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CoverFeatureId { get; set; }
#nullable restore
#else
        public string CoverFeatureId { get; set; }
#endif
        /// <summary>是否生成纯音乐（无人声）。仅 `music-2.6` / `music-2.6-free` 支持。设为 `true` 时，`lyrics` 字段非必填。默认为 `false`</summary>
        public bool? IsInstrumental { get; set; }
        /// <summary>歌曲歌词，使用 `\n` 分隔每行。支持结构标签：`[Intro]`, `[Verse]`, `[Pre Chorus]`, `[Chorus]`, `[Interlude]`, `[Bridge]`, `[Outro]`, `[Post Chorus]`, `[Transition]`, `[Break]`, `[Hook]`, `[Build Up]`, `[Inst]`, `[Solo]`。&lt;br&gt;注意：- `music-2.6` / `music-2.6-free` 纯音乐（`is_instrumental: true`）：非必填- `music-2.6` / `music-2.6-free`（非纯音乐）：必填，长度限制 [1, 3500] 个字符- `music-cover` / `music-cover-free`：可选，如不传则通过 ASR 自动从参考音频中提取歌词，长度限制 [10, 1000] 个字符- 当 `lyrics_optimizer: true` 且 `lyrics` 为空时，系统将根据 `prompt` 自动生成歌词</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lyrics { get; set; }
#nullable restore
#else
        public string Lyrics { get; set; }
#endif
        /// <summary>是否根据 `prompt` 描述自动生成歌词。仅 `music-2.6` / `music-2.6-free` 支持。设为 `true` 且 `lyrics` 为空时，系统会根据 prompt 自动生成歌词。默认为 `false`</summary>
        public bool? LyricsOptimizer { get; set; }
        /// <summary>使用的模型名称。可选值：- `music-2.6`（推荐）：文本生成音乐，仅限 Token Plan 用户和付费用户使用，RPM 较高- `music-cover`：基于参考音频生成翻唱版本，仅限 Token Plan 用户和付费用户使用，RPM 较高- `music-2.6-free`：`music-2.6` 的限免版本，所有用户可通过 API Key 使用，RPM 较低- `music-cover-free`：`music-cover` 的限免版本，所有用户可通过 API Key 使用，RPM 较低</summary>
        public global::MiniMax.Models.GenerateMusicReq_model? Model { get; set; }
        /// <summary>音频的返回格式，可选值为 `url` 或 `hex`，默认为 `hex`。当 `stream` 为 `true` 时，仅支持 `hex` 格式。注意：url 的有效期为 24 小时，请及时下载</summary>
        public global::MiniMax.Models.GenerateMusicReq_output_format? OutputFormat { get; set; }
        /// <summary>音乐的描述，用于指定风格、情绪和场景。例如&quot;流行音乐, 难过, 适合在下雨的晚上&quot;。&lt;br&gt;注意：- `music-2.6` / `music-2.6-free` 纯音乐（`is_instrumental: true`）：必填，长度限制 [1, 2000] 个字符- `music-2.6` / `music-2.6-free`（非纯音乐）：可选，长度限制 [0, 2000] 个字符- `music-cover` / `music-cover-free`：必填，描述目标翻唱风格，长度限制 [10, 300] 个字符</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>是否使用流式传输，默认为 `false`</summary>
        public bool? Stream { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.GenerateMusicReq"/> and sets the default values.
        /// </summary>
        public GenerateMusicReq()
        {
            AdditionalData = new Dictionary<string, object>();
            OutputFormat = global::MiniMax.Models.GenerateMusicReq_output_format.Hex;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.GenerateMusicReq"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.GenerateMusicReq CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.GenerateMusicReq();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aigc_watermark", n => { AigcWatermark = n.GetBoolValue(); } },
                { "audio_base64", n => { AudioBase64 = n.GetStringValue(); } },
                { "audio_setting", n => { AudioSetting = n.GetObjectValue<global::MiniMax.Models.AudioSetting>(global::MiniMax.Models.AudioSetting.CreateFromDiscriminatorValue); } },
                { "audio_url", n => { AudioUrl = n.GetStringValue(); } },
                { "cover_feature_id", n => { CoverFeatureId = n.GetStringValue(); } },
                { "is_instrumental", n => { IsInstrumental = n.GetBoolValue(); } },
                { "lyrics", n => { Lyrics = n.GetStringValue(); } },
                { "lyrics_optimizer", n => { LyricsOptimizer = n.GetBoolValue(); } },
                { "model", n => { Model = n.GetEnumValue<global::MiniMax.Models.GenerateMusicReq_model>(); } },
                { "output_format", n => { OutputFormat = n.GetEnumValue<global::MiniMax.Models.GenerateMusicReq_output_format>(); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "stream", n => { Stream = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("aigc_watermark", AigcWatermark);
            writer.WriteStringValue("audio_base64", AudioBase64);
            writer.WriteObjectValue<global::MiniMax.Models.AudioSetting>("audio_setting", AudioSetting);
            writer.WriteStringValue("audio_url", AudioUrl);
            writer.WriteStringValue("cover_feature_id", CoverFeatureId);
            writer.WriteBoolValue("is_instrumental", IsInstrumental);
            writer.WriteStringValue("lyrics", Lyrics);
            writer.WriteBoolValue("lyrics_optimizer", LyricsOptimizer);
            writer.WriteEnumValue<global::MiniMax.Models.GenerateMusicReq_model>("model", Model);
            writer.WriteEnumValue<global::MiniMax.Models.GenerateMusicReq_output_format>("output_format", OutputFormat);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteBoolValue("stream", Stream);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
