// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>音频的返回格式，可选值为 `url` 或 `hex`，默认为 `hex`。当 `stream` 为 `true` 时，仅支持 `hex` 格式。注意：url 的有效期为 24 小时，请及时下载</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GenerateMusicReq_output_format
    {
        [EnumMember(Value = "url")]
        #pragma warning disable CS1591
        Url,
        #pragma warning restore CS1591
        [EnumMember(Value = "hex")]
        #pragma warning disable CS1591
        Hex,
        #pragma warning restore CS1591
    }
}
