// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GenerateLyricsReq : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>现有歌词内容，仅在 `edit` 模式下有效。可用于续写或修改已有歌词。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lyrics { get; set; }
#nullable restore
#else
        public string Lyrics { get; set; }
#endif
        /// <summary>生成模式。&lt;br&gt;`write_full_song`：写完整歌曲&lt;br&gt;`edit`：编辑/续写歌词</summary>
        public global::MiniMax.Models.GenerateLyricsReq_mode? Mode { get; set; }
        /// <summary>提示词/指令，用于描述歌曲主题、风格或编辑方向。为空时随机生成。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>歌曲标题。传入后输出将保持该标题不变。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.GenerateLyricsReq"/> and sets the default values.
        /// </summary>
        public GenerateLyricsReq()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.GenerateLyricsReq"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.GenerateLyricsReq CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.GenerateLyricsReq();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "lyrics", n => { Lyrics = n.GetStringValue(); } },
                { "mode", n => { Mode = n.GetEnumValue<global::MiniMax.Models.GenerateLyricsReq_mode>(); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("lyrics", Lyrics);
            writer.WriteEnumValue<global::MiniMax.Models.GenerateLyricsReq_mode>("mode", Mode);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
