// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GenerateLyricsResp : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>状态码及详情</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.BaseResp? BaseResp { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.BaseResp BaseResp { get; set; }
#endif
        /// <summary>生成的歌词，包含结构标签。可直接用于[音乐生成接口](/api-reference/music-generation)的 `lyrics` 参数生成歌曲。&lt;br&gt;支持的结构标签（14种）：`[Intro]`, `[Verse]`, `[Pre-Chorus]`, `[Chorus]`, `[Hook]`, `[Drop]`, `[Bridge]`, `[Solo]`, `[Build-up]`, `[Instrumental]`, `[Breakdown]`, `[Break]`, `[Interlude]`, `[Outro]`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lyrics { get; set; }
#nullable restore
#else
        public string Lyrics { get; set; }
#endif
        /// <summary>生成的歌名。若请求传入 `title` 则保持一致。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SongTitle { get; set; }
#nullable restore
#else
        public string SongTitle { get; set; }
#endif
        /// <summary>风格标签，逗号分隔。例如：`Pop, Upbeat, Female Vocals`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StyleTags { get; set; }
#nullable restore
#else
        public string StyleTags { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.GenerateLyricsResp"/> and sets the default values.
        /// </summary>
        public GenerateLyricsResp()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.GenerateLyricsResp"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.GenerateLyricsResp CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.GenerateLyricsResp();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base_resp", n => { BaseResp = n.GetObjectValue<global::MiniMax.Models.BaseResp>(global::MiniMax.Models.BaseResp.CreateFromDiscriminatorValue); } },
                { "lyrics", n => { Lyrics = n.GetStringValue(); } },
                { "song_title", n => { SongTitle = n.GetStringValue(); } },
                { "style_tags", n => { StyleTags = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MiniMax.Models.BaseResp>("base_resp", BaseResp);
            writer.WriteStringValue("lyrics", Lyrics);
            writer.WriteStringValue("song_title", SongTitle);
            writer.WriteStringValue("style_tags", StyleTags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
