// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>生成模式。&lt;br&gt;`write_full_song`：写完整歌曲&lt;br&gt;`edit`：编辑/续写歌词</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GenerateLyricsReq_mode
    {
        [EnumMember(Value = "write_full_song")]
        #pragma warning disable CS1591
        Write_full_song,
        #pragma warning restore CS1591
        [EnumMember(Value = "edit")]
        #pragma warning disable CS1591
        Edit,
        #pragma warning restore CS1591
    }
}
