// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetVoiceResp : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>状态码及详情</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.BaseResp? BaseResp { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.BaseResp BaseResp { get; set; }
#endif
        /// <summary>包含系统预定义的音色。</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MiniMax.Models.SystemVoiceInfo>? SystemVoice { get; set; }
#nullable restore
#else
        public List<global::MiniMax.Models.SystemVoiceInfo> SystemVoice { get; set; }
#endif
        /// <summary>包含音色快速复刻的音色数据</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MiniMax.Models.VoiceCloningInfo>? VoiceCloning { get; set; }
#nullable restore
#else
        public List<global::MiniMax.Models.VoiceCloningInfo> VoiceCloning { get; set; }
#endif
        /// <summary>包含音色生成接口产生的音色数据</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MiniMax.Models.VoiceGenerationInfo>? VoiceGeneration { get; set; }
#nullable restore
#else
        public List<global::MiniMax.Models.VoiceGenerationInfo> VoiceGeneration { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.GetVoiceResp"/> and sets the default values.
        /// </summary>
        public GetVoiceResp()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.GetVoiceResp"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.GetVoiceResp CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.GetVoiceResp();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base_resp", n => { BaseResp = n.GetObjectValue<global::MiniMax.Models.BaseResp>(global::MiniMax.Models.BaseResp.CreateFromDiscriminatorValue); } },
                { "system_voice", n => { SystemVoice = n.GetCollectionOfObjectValues<global::MiniMax.Models.SystemVoiceInfo>(global::MiniMax.Models.SystemVoiceInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "voice_cloning", n => { VoiceCloning = n.GetCollectionOfObjectValues<global::MiniMax.Models.VoiceCloningInfo>(global::MiniMax.Models.VoiceCloningInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "voice_generation", n => { VoiceGeneration = n.GetCollectionOfObjectValues<global::MiniMax.Models.VoiceGenerationInfo>(global::MiniMax.Models.VoiceGenerationInfo.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MiniMax.Models.BaseResp>("base_resp", BaseResp);
            writer.WriteCollectionOfObjectValues<global::MiniMax.Models.SystemVoiceInfo>("system_voice", SystemVoice);
            writer.WriteCollectionOfObjectValues<global::MiniMax.Models.VoiceCloningInfo>("voice_cloning", VoiceCloning);
            writer.WriteCollectionOfObjectValues<global::MiniMax.Models.VoiceGenerationInfo>("voice_generation", VoiceGeneration);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
