// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>希望查询音色类型，支持以下取值：- `system`: 系统音色- `voice_cloning`: 快速复刻的音色，仅在成功用于语音合成后才可查询- `voice_generation`: 文生音色接口生成的音色，仅在成功用于语音合成后才可查询- `all`: 以上全部</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetVoiceReq_voice_type
    {
        [EnumMember(Value = "system")]
        #pragma warning disable CS1591
        System,
        #pragma warning restore CS1591
        [EnumMember(Value = "voice_cloning")]
        #pragma warning disable CS1591
        Voice_cloning,
        #pragma warning restore CS1591
        [EnumMember(Value = "voice_generation")]
        #pragma warning disable CS1591
        Voice_generation,
        #pragma warning restore CS1591
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
    }
}
