// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ImageGenerationReq : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>是否在生成的图片中添加水印，默认为 `false`</summary>
        public bool? AigcWatermark { get; set; }
        /// <summary>图像宽高比，默认为 1:1。可选值：- `1:1` (1024x1024)- `16:9` (1280x720)- `4:3` (1152x864)- `3:2` (1248x832)- `2:3` (832x1248)- `3:4` (864x1152)- `9:16` (720x1280)- `21:9` (1344x576) (仅适用于`image-01`)</summary>
        public global::MiniMax.Models.ImageGenerationReq_aspect_ratio? AspectRatio { get; set; }
        /// <summary>生成图片的高度（像素）。仅当 model 为 `image-01` 时生效。注意：`width` 和 `height` 需同时设置，取值范围[512, 2048]，且必须是 8 的倍数。若与 `aspect_ratio` 同时设置，则优先使用 `aspect_ratio`</summary>
        public int? Height { get; set; }
        /// <summary>模型名称。可选值：`image-01`，`image-01-live`</summary>
        public global::MiniMax.Models.ImageGenerationReq_model? Model { get; set; }
        /// <summary>单次请求生成的图片数量，取值范围[1, 9]，默认为 1</summary>
        public int? N { get; set; }
        /// <summary>图像的文本描述，最长 1500 字符</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>是否开启 prompt 自动优化，默认为 `false`.</summary>
        public bool? PromptOptimizer { get; set; }
        /// <summary>返回图片的形式，默认为 url。可选值：url, base64。⚠️ 注意：url 的有效期为 24 小时</summary>
        public global::MiniMax.Models.ImageGenerationReq_response_format? ResponseFormat { get; set; }
        /// <summary>随机种子。使用相同的 seed 和参数，可以生成内容相近的图片，用于复现结果。如未提供，算法会对 n 张图单独生成随机种子</summary>
        public long? Seed { get; set; }
        /// <summary>画风设置，仅当 `model` 为 `image-01-live` 时生效</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.StyleObject? Style { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.StyleObject Style { get; set; }
#endif
        /// <summary>生成图片的宽度（像素）。仅当 model 为 `image-01` 时生效。注意：`width` 和 `height` 需同时设置，取值范围[512, 2048]，且必须是 8 的倍数。若与 `aspect_ratio` 同时设置，则优先使用 `aspect_ratio`</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.ImageGenerationReq"/> and sets the default values.
        /// </summary>
        public ImageGenerationReq()
        {
            AdditionalData = new Dictionary<string, object>();
            ResponseFormat = global::MiniMax.Models.ImageGenerationReq_response_format.Url;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.ImageGenerationReq"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.ImageGenerationReq CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.ImageGenerationReq();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aigc_watermark", n => { AigcWatermark = n.GetBoolValue(); } },
                { "aspect_ratio", n => { AspectRatio = n.GetEnumValue<global::MiniMax.Models.ImageGenerationReq_aspect_ratio>(); } },
                { "height", n => { Height = n.GetIntValue(); } },
                { "model", n => { Model = n.GetEnumValue<global::MiniMax.Models.ImageGenerationReq_model>(); } },
                { "n", n => { N = n.GetIntValue(); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "prompt_optimizer", n => { PromptOptimizer = n.GetBoolValue(); } },
                { "response_format", n => { ResponseFormat = n.GetEnumValue<global::MiniMax.Models.ImageGenerationReq_response_format>(); } },
                { "seed", n => { Seed = n.GetLongValue(); } },
                { "style", n => { Style = n.GetObjectValue<global::MiniMax.Models.StyleObject>(global::MiniMax.Models.StyleObject.CreateFromDiscriminatorValue); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("aigc_watermark", AigcWatermark);
            writer.WriteEnumValue<global::MiniMax.Models.ImageGenerationReq_aspect_ratio>("aspect_ratio", AspectRatio);
            writer.WriteIntValue("height", Height);
            writer.WriteEnumValue<global::MiniMax.Models.ImageGenerationReq_model>("model", Model);
            writer.WriteIntValue("n", N);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteBoolValue("prompt_optimizer", PromptOptimizer);
            writer.WriteEnumValue<global::MiniMax.Models.ImageGenerationReq_response_format>("response_format", ResponseFormat);
            writer.WriteLongValue("seed", Seed);
            writer.WriteObjectValue<global::MiniMax.Models.StyleObject>("style", Style);
            writer.WriteIntValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
