// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>图像宽高比，默认为 1:1。可选值：- `1:1` (1024x1024)- `16:9` (1280x720)- `4:3` (1152x864)- `3:2` (1248x832)- `2:3` (832x1248)- `3:4` (864x1152)- `9:16` (720x1280)- `21:9` (1344x576) (仅适用于`image-01`)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ImageGenerationReq_aspect_ratio
    {
        [EnumMember(Value = "1:1")]
        #pragma warning disable CS1591
        OneOne,
        #pragma warning restore CS1591
        [EnumMember(Value = "16:9")]
        #pragma warning disable CS1591
        OneSixNine,
        #pragma warning restore CS1591
        [EnumMember(Value = "4:3")]
        #pragma warning disable CS1591
        FourThree,
        #pragma warning restore CS1591
        [EnumMember(Value = "3:2")]
        #pragma warning disable CS1591
        ThreeTwo,
        #pragma warning restore CS1591
        [EnumMember(Value = "2:3")]
        #pragma warning disable CS1591
        TwoThree,
        #pragma warning restore CS1591
        [EnumMember(Value = "3:4")]
        #pragma warning disable CS1591
        ThreeFour,
        #pragma warning restore CS1591
        [EnumMember(Value = "9:16")]
        #pragma warning disable CS1591
        NineOneSix,
        #pragma warning restore CS1591
        [EnumMember(Value = "21:9")]
        #pragma warning disable CS1591
        TwoOneNine,
        #pragma warning restore CS1591
    }
}
