// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>模型名称。可选值：`image-01`，`image-01-live`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ImageGenerationReq_model
    {
        [EnumMember(Value = "image-01")]
        #pragma warning disable CS1591
        Image01,
        #pragma warning restore CS1591
        [EnumMember(Value = "image-01-live")]
        #pragma warning disable CS1591
        Image01Live,
        #pragma warning restore CS1591
    }
}
