// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>消息发送者的角色- `user`: 用户的输入- `assistant`: 模型的历史回复- `user_system`: 设定用户的角色和人设- `group`: 对话的名称- `sample_message_user`: 示例的用户输入- `sample_message_ai`: 示例的模型输出</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Message_role
    {
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "assistant")]
        #pragma warning disable CS1591
        Assistant,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_system")]
        #pragma warning disable CS1591
        User_system,
        #pragma warning restore CS1591
        [EnumMember(Value = "group")]
        #pragma warning disable CS1591
        Group,
        #pragma warning restore CS1591
        [EnumMember(Value = "sample_message_user")]
        #pragma warning disable CS1591
        Sample_message_user,
        #pragma warning restore CS1591
        [EnumMember(Value = "sample_message_ai")]
        #pragma warning disable CS1591
        Sample_message_ai,
        #pragma warning restore CS1591
    }
}
