// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QueryVideoGenerationTaskResp : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The base_resp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.QueryVideoGenerationTaskBaseResp? BaseResp { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.QueryVideoGenerationTaskBaseResp BaseResp { get; set; }
#endif
        /// <summary>任务成功时返回，用于获取视频文件的文件 ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileId { get; set; }
#nullable restore
#else
        public string FileId { get; set; }
#endif
        /// <summary>任务的当前状态。可能的状态值包括：- `Preparing` – 准备中- `Queueing` – 队列中- `Processing` – 生成中- `Success` – 成功- `Fail` – 失败</summary>
        public global::MiniMax.Models.VideoProcessStatus? Status { get; set; }
        /// <summary>被查询的任务 ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskId { get; set; }
#nullable restore
#else
        public string TaskId { get; set; }
#endif
        /// <summary>任务成功时返回，生成视频的高度（像素）</summary>
        public int? VideoHeight { get; set; }
        /// <summary>任务成功时返回，生成视频的宽度（像素）.</summary>
        public int? VideoWidth { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.QueryVideoGenerationTaskResp"/> and sets the default values.
        /// </summary>
        public QueryVideoGenerationTaskResp()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.QueryVideoGenerationTaskResp"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.QueryVideoGenerationTaskResp CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.QueryVideoGenerationTaskResp();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base_resp", n => { BaseResp = n.GetObjectValue<global::MiniMax.Models.QueryVideoGenerationTaskBaseResp>(global::MiniMax.Models.QueryVideoGenerationTaskBaseResp.CreateFromDiscriminatorValue); } },
                { "file_id", n => { FileId = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::MiniMax.Models.VideoProcessStatus>(); } },
                { "task_id", n => { TaskId = n.GetStringValue(); } },
                { "video_height", n => { VideoHeight = n.GetIntValue(); } },
                { "video_width", n => { VideoWidth = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MiniMax.Models.QueryVideoGenerationTaskBaseResp>("base_resp", BaseResp);
            writer.WriteStringValue("file_id", FileId);
            writer.WriteEnumValue<global::MiniMax.Models.VideoProcessStatus>("status", Status);
            writer.WriteStringValue("task_id", TaskId);
            writer.WriteIntValue("video_height", VideoHeight);
            writer.WriteIntValue("video_width", VideoWidth);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
