// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>控制合成语音的情绪，参数范围 `[&quot;happy&quot;, &quot;sad&quot;, &quot;angry&quot;, &quot;fearful&quot;, &quot;disgusted&quot;, &quot;surprised&quot;, &quot;calm&quot;, &quot;fluent&quot;, &quot;whisper&quot;]`，分别对应 8 种情绪：高兴，悲伤，愤怒，害怕，厌恶，惊讶，中性，生动，低语 - 模型会根据输入文本自动匹配合适的情绪，一般无需手动指定  - 该参数仅对 `speech-2.8-hd`, `speech-2.8-turbo`, `speech-2.6-hd`, `speech-2.6-turbo`, `speech-02-hd`, `speech-02-turbo`, `speech-01-hd`, `speech-01-turbo` 模型生效 - 选项 `fluent`, `whisper` 仅对 `speech-2.6-turbo`, `speech-2.6-hd` 模型生效，`speech-2.8-hd`, `speech-2.8-turbo` 模型不支持 `whisper`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum T2AAsyncV2VoiceSetting_emotion
    {
        [EnumMember(Value = "happy")]
        #pragma warning disable CS1591
        Happy,
        #pragma warning restore CS1591
        [EnumMember(Value = "sad")]
        #pragma warning disable CS1591
        Sad,
        #pragma warning restore CS1591
        [EnumMember(Value = "angry")]
        #pragma warning disable CS1591
        Angry,
        #pragma warning restore CS1591
        [EnumMember(Value = "fearful")]
        #pragma warning disable CS1591
        Fearful,
        #pragma warning restore CS1591
        [EnumMember(Value = "disgusted")]
        #pragma warning disable CS1591
        Disgusted,
        #pragma warning restore CS1591
        [EnumMember(Value = "surprised")]
        #pragma warning disable CS1591
        Surprised,
        #pragma warning restore CS1591
        [EnumMember(Value = "calm")]
        #pragma warning disable CS1591
        Calm,
        #pragma warning restore CS1591
        [EnumMember(Value = "fluent")]
        #pragma warning disable CS1591
        Fluent,
        #pragma warning restore CS1591
        [EnumMember(Value = "whisper")]
        #pragma warning disable CS1591
        Whisper,
        #pragma warning restore CS1591
    }
}
