// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>生成音频的格式，`wav` 仅在非流式输出下支持</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum T2AAudioSetting_format
    {
        [EnumMember(Value = "mp3")]
        #pragma warning disable CS1591
        Mp3,
        #pragma warning restore CS1591
        [EnumMember(Value = "pcm")]
        #pragma warning disable CS1591
        Pcm,
        #pragma warning restore CS1591
        [EnumMember(Value = "flac")]
        #pragma warning disable CS1591
        Flac,
        #pragma warning restore CS1591
        [EnumMember(Value = "wav")]
        #pragma warning disable CS1591
        Wav,
        #pragma warning restore CS1591
    }
}
