// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>请求的模型版本，可选范围：`speech-2.8-hd`, `speech-2.8-turbo`, `speech-2.6-hd`, `speech-2.6-turbo`, `speech-02-hd`, `speech-02-turbo`, `speech-01-hd`, `speech-01-turbo`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum T2AAsyncV2Req_model
    {
        [EnumMember(Value = "speech-2.8-hd")]
        #pragma warning disable CS1591
        Speech28Hd,
        #pragma warning restore CS1591
        [EnumMember(Value = "speech-2.8-turbo")]
        #pragma warning disable CS1591
        Speech28Turbo,
        #pragma warning restore CS1591
        [EnumMember(Value = "speech-2.6-hd")]
        #pragma warning disable CS1591
        Speech26Hd,
        #pragma warning restore CS1591
        [EnumMember(Value = "speech-2.6-turbo")]
        #pragma warning disable CS1591
        Speech26Turbo,
        #pragma warning restore CS1591
        [EnumMember(Value = "speech-02-hd")]
        #pragma warning disable CS1591
        Speech02Hd,
        #pragma warning restore CS1591
        [EnumMember(Value = "speech-02-turbo")]
        #pragma warning disable CS1591
        Speech02Turbo,
        #pragma warning restore CS1591
        [EnumMember(Value = "speech-01-hd")]
        #pragma warning disable CS1591
        Speech01Hd,
        #pragma warning restore CS1591
        [EnumMember(Value = "speech-01-turbo")]
        #pragma warning disable CS1591
        Speech01Turbo,
        #pragma warning restore CS1591
    }
}
