// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class T2AAsyncV2Req : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>控制在合成音频的末尾添加音频节奏标识，默认值为 False。该参数仅对非流式合成生效</summary>
        public bool? AigcWatermark { get; set; }
        /// <summary>The audio_setting property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.T2AAsyncV2AudioSetting? AudioSetting { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.T2AAsyncV2AudioSetting AudioSetting { get; set; }
#endif
        /// <summary>是否增强对指定的小语种和方言的识别能力。默认值为 `null`，可设置为 `auto` 让模型自主判断。注意：speech-01 和 speech-02 系列模型暂不支持 Persian、Filipino、Tamil 这三个语种。</summary>
        public global::MiniMax.Models.T2AAsyncV2Req_language_boost? LanguageBoost { get; set; }
        /// <summary>请求的模型版本，可选范围：`speech-2.8-hd`, `speech-2.8-turbo`, `speech-2.6-hd`, `speech-2.6-turbo`, `speech-02-hd`, `speech-02-turbo`, `speech-01-hd`, `speech-01-turbo`.</summary>
        public global::MiniMax.Models.T2AAsyncV2Req_model? Model { get; set; }
        /// <summary>The pronunciation_dict property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.T2AAsyncV2PronunciationDict? PronunciationDict { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.T2AAsyncV2PronunciationDict PronunciationDict { get; set; }
#endif
        /// <summary>待合成音频的文本，限制最长 5 万字符。和 `text_file_id` 二选一必填- 语气词标签：仅当模型选择 `speech-2.8-hd` 或 `speech-2.8-turbo` 时，支持在文本中插入语气词标签。支持的语气词：`(laughs)`（笑声）、`(chuckle)`（轻笑）、`(coughs)`（咳嗽）、`(clear-throat)`（清嗓子）、`(groans)`（呻吟）、`(breath)`（正常换气）、`(pant)`（喘气）、`(inhale)`（吸气）、`(exhale)`（呼气）、`(gasps)`（倒吸气）、`(sniffs)`（吸鼻子）、`(sighs)`（叹气）、`(snorts)`（喷鼻息）、`(burps)`（打嗝）、`(lip-smacking)`（咂嘴）、`(humming)`（哼唱）、`(hissing)`（嘶嘶声）、`(emm)`（嗯）、`(whistles)`（口哨）、`(sneezes)`（喷嚏）、`(crying)`（抽泣）、`(applause)`（鼓掌）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>待合成音频的文本文件 待合成音频的文本文件 id，单个文件长度限制小于 10 万字符，支持的文件格式：txt、zip。和 `text` 二选一必填，传入后自动校验格式。- **txt 文件**：长度限制 &lt;100,000 字符。支持使用 &lt;#x#&gt; 标记自定义停顿。x 为停顿时长（单位：秒），范围 [0.01,99.99]，最多保留两位小数。注意停顿需设置在两个可以语音发音的文本之间，不可连续使用多个停顿标记- **zip 文件**：- 压缩包内需包含同一格式的 txt 或 json 文件。- json 文件格式：支持 [`title`, `content`, `extra`] 三个字段，分别表示标题、正文、附加信息。若三个字段都存在，则产出 3 组结果，共 9 个文件，统一存放在一个文件夹中。若某字段不存在或内容为空，则该字段不会生成对应结果</summary>
        public long? TextFileId { get; set; }
        /// <summary>声音效果器设置</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.VoiceModify? VoiceModify { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.VoiceModify VoiceModify { get; set; }
#endif
        /// <summary>The voice_setting property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.T2AAsyncV2VoiceSetting? VoiceSetting { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.T2AAsyncV2VoiceSetting VoiceSetting { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.T2AAsyncV2Req"/> and sets the default values.
        /// </summary>
        public T2AAsyncV2Req()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.T2AAsyncV2Req"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.T2AAsyncV2Req CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.T2AAsyncV2Req();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aigc_watermark", n => { AigcWatermark = n.GetBoolValue(); } },
                { "audio_setting", n => { AudioSetting = n.GetObjectValue<global::MiniMax.Models.T2AAsyncV2AudioSetting>(global::MiniMax.Models.T2AAsyncV2AudioSetting.CreateFromDiscriminatorValue); } },
                { "language_boost", n => { LanguageBoost = n.GetEnumValue<global::MiniMax.Models.T2AAsyncV2Req_language_boost>(); } },
                { "model", n => { Model = n.GetEnumValue<global::MiniMax.Models.T2AAsyncV2Req_model>(); } },
                { "pronunciation_dict", n => { PronunciationDict = n.GetObjectValue<global::MiniMax.Models.T2AAsyncV2PronunciationDict>(global::MiniMax.Models.T2AAsyncV2PronunciationDict.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "text_file_id", n => { TextFileId = n.GetLongValue(); } },
                { "voice_modify", n => { VoiceModify = n.GetObjectValue<global::MiniMax.Models.VoiceModify>(global::MiniMax.Models.VoiceModify.CreateFromDiscriminatorValue); } },
                { "voice_setting", n => { VoiceSetting = n.GetObjectValue<global::MiniMax.Models.T2AAsyncV2VoiceSetting>(global::MiniMax.Models.T2AAsyncV2VoiceSetting.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("aigc_watermark", AigcWatermark);
            writer.WriteObjectValue<global::MiniMax.Models.T2AAsyncV2AudioSetting>("audio_setting", AudioSetting);
            writer.WriteEnumValue<global::MiniMax.Models.T2AAsyncV2Req_language_boost>("language_boost", LanguageBoost);
            writer.WriteEnumValue<global::MiniMax.Models.T2AAsyncV2Req_model>("model", Model);
            writer.WriteObjectValue<global::MiniMax.Models.T2AAsyncV2PronunciationDict>("pronunciation_dict", PronunciationDict);
            writer.WriteStringValue("text", Text);
            writer.WriteLongValue("text_file_id", TextFileId);
            writer.WriteObjectValue<global::MiniMax.Models.VoiceModify>("voice_modify", VoiceModify);
            writer.WriteObjectValue<global::MiniMax.Models.T2AAsyncV2VoiceSetting>("voice_setting", VoiceSetting);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
