// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class T2AAsyncV2VoiceSetting : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>控制合成语音的情绪，参数范围 `[&quot;happy&quot;, &quot;sad&quot;, &quot;angry&quot;, &quot;fearful&quot;, &quot;disgusted&quot;, &quot;surprised&quot;, &quot;calm&quot;, &quot;fluent&quot;, &quot;whisper&quot;]`，分别对应 8 种情绪：高兴，悲伤，愤怒，害怕，厌恶，惊讶，中性，生动，低语 - 模型会根据输入文本自动匹配合适的情绪，一般无需手动指定  - 该参数仅对 `speech-2.8-hd`, `speech-2.8-turbo`, `speech-2.6-hd`, `speech-2.6-turbo`, `speech-02-hd`, `speech-02-turbo`, `speech-01-hd`, `speech-01-turbo` 模型生效 - 选项 `fluent`, `whisper` 仅对 `speech-2.6-turbo`, `speech-2.6-hd` 模型生效，`speech-2.8-hd`, `speech-2.8-turbo` 模型不支持 `whisper`</summary>
        public global::MiniMax.Models.T2AAsyncV2VoiceSetting_emotion? Emotion { get; set; }
        /// <summary>支持英语文本规范化，开启后可提升数字阅读场景的性能，但会略微增加延迟，默认 false</summary>
        public bool? EnglishNormalization { get; set; }
        /// <summary>合成音频的语调，取值范围 `[-12,12]`，默认值为 0，其中 0 为原音色输出</summary>
        public int? Pitch { get; set; }
        /// <summary>合成音频的语速，取值越大，语速越快。取值范围 `[0.5,2]`，默认值为1.0</summary>
        public float? Speed { get; set; }
        /// <summary>合成音频的音色编号。若需要设置混合音色，请设置 timbre_weights 参数，本参数设置为空值。支持系统音色、复刻音色以及文生音色三种类型，以下是部分最新的系统音色（ID），可查看 [系统音色列表](/faq/system-voice-id) 或使用 [查询可用音色 API](/api-reference/voice-management-get) 查询系统支持的全部音色 - **中文**:- moss_audio_ce44fc67-7ce3-11f0-8de5-96e35d26fb85- moss_audio_aaa1346a-7ce7-11f0-8e61-2e6e3c7ee85d- Chinese (Mandarin)_Lyrical_Voice- Chinese (Mandarin)_HK_Flight_Attendant- **英文**:- English_Graceful_Lady- English_Insightful_Speaker- English_radiant_girl- English_Persuasive_Man- moss_audio_6dc281eb-713c-11f0-a447-9613c873494c- moss_audio_570551b1-735c-11f0-b236-0adeeecad052- moss_audio_ad5baf92-735f-11f0-8263-fe5a2fe98ec8- English_Lucky_Robot- **日文**:- Japanese_Whisper_Belle- moss_audio_24875c4a-7be4-11f0-9359-4e72c55db738- moss_audio_7f4ee608-78ea-11f0-bb73-1e2a4cfcd245- moss_audio_c1a6a3ac-7be6-11f0-8e8e-36b92fbb4f95</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VoiceId { get; set; }
#nullable restore
#else
        public string VoiceId { get; set; }
#endif
        /// <summary>合成音频的音量，取值越大，音量越高。取值范围 `(0,10]`，默认值为 1.0</summary>
        public float? Vol { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.T2AAsyncV2VoiceSetting"/> and sets the default values.
        /// </summary>
        public T2AAsyncV2VoiceSetting()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.T2AAsyncV2VoiceSetting"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.T2AAsyncV2VoiceSetting CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.T2AAsyncV2VoiceSetting();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "emotion", n => { Emotion = n.GetEnumValue<global::MiniMax.Models.T2AAsyncV2VoiceSetting_emotion>(); } },
                { "english_normalization", n => { EnglishNormalization = n.GetBoolValue(); } },
                { "pitch", n => { Pitch = n.GetIntValue(); } },
                { "speed", n => { Speed = n.GetFloatValue(); } },
                { "voice_id", n => { VoiceId = n.GetStringValue(); } },
                { "vol", n => { Vol = n.GetFloatValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::MiniMax.Models.T2AAsyncV2VoiceSetting_emotion>("emotion", Emotion);
            writer.WriteBoolValue("english_normalization", EnglishNormalization);
            writer.WriteIntValue("pitch", Pitch);
            writer.WriteFloatValue("speed", Speed);
            writer.WriteStringValue("voice_id", VoiceId);
            writer.WriteFloatValue("vol", Vol);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
