// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class T2AAsyncV2AudioSetting : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>生成音频的采样率。可选范围 `[8000，16000，22050，24000，32000，44100]`，默认为 `32000`</summary>
        public long? AudioSampleRate { get; set; }
        /// <summary>生成音频的比特率。可选范围 `[32000，64000，128000，256000]`，默认值为 `128000`。该参数仅对 `mp3` 格式的音频生效</summary>
        public long? Bitrate { get; set; }
        /// <summary>生成音频的声道数。可选范围：`[1,2]`，其中 `1` 为单声道，`2` 为双声道，默认值为 1</summary>
        public long? Channel { get; set; }
        /// <summary>生成音频的格式。可选范围`[mp3, pcm, flac]`，默认值为 `mp3`</summary>
        public global::MiniMax.Models.T2AAsyncV2AudioSetting_format? Format { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.T2AAsyncV2AudioSetting"/> and sets the default values.
        /// </summary>
        public T2AAsyncV2AudioSetting()
        {
            AdditionalData = new Dictionary<string, object>();
            Format = global::MiniMax.Models.T2AAsyncV2AudioSetting_format.Mp3;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.T2AAsyncV2AudioSetting"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.T2AAsyncV2AudioSetting CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.T2AAsyncV2AudioSetting();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audio_sample_rate", n => { AudioSampleRate = n.GetLongValue(); } },
                { "bitrate", n => { Bitrate = n.GetLongValue(); } },
                { "channel", n => { Channel = n.GetLongValue(); } },
                { "format", n => { Format = n.GetEnumValue<global::MiniMax.Models.T2AAsyncV2AudioSetting_format>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("audio_sample_rate", AudioSampleRate);
            writer.WriteLongValue("bitrate", Bitrate);
            writer.WriteLongValue("channel", Channel);
            writer.WriteEnumValue<global::MiniMax.Models.T2AAsyncV2AudioSetting_format>("format", Format);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
