// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>生成音频的格式。可选范围`[mp3, pcm, flac]`，默认值为 `mp3`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum T2AAsyncV2AudioSetting_format
    {
        [EnumMember(Value = "mp3")]
        #pragma warning disable CS1591
        Mp3,
        #pragma warning restore CS1591
        [EnumMember(Value = "pcm")]
        #pragma warning disable CS1591
        Pcm,
        #pragma warning restore CS1591
        [EnumMember(Value = "flac")]
        #pragma warning disable CS1591
        Flac,
        #pragma warning restore CS1591
    }
}
