// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class T2AAsyncV2Resp : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>状态码及详情</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.BaseResp? BaseResp { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.BaseResp BaseResp { get; set; }
#endif
        /// <summary>任务创建成功后返回的对应音频文件的 ID。- 当任务完成后，可通过 file_id 调用 [文件检索接口](/api-reference/file-management-retrieve) 进行下载- 当请求出错时，不返回该字段注意：返回的下载 URL 自生成起 9 小时（32,400 秒）内有效，过期后文件将失效，生成的信息便会丢失，请注意下载信息的时间</summary>
        public long? FileId { get; set; }
        /// <summary>当前任务的 ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskId { get; set; }
#nullable restore
#else
        public string TaskId { get; set; }
#endif
        /// <summary>完成当前任务使用的密钥信息</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskToken { get; set; }
#nullable restore
#else
        public string TaskToken { get; set; }
#endif
        /// <summary>计费字符数</summary>
        public int? UsageCharacters { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.T2AAsyncV2Resp"/> and sets the default values.
        /// </summary>
        public T2AAsyncV2Resp()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.T2AAsyncV2Resp"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.T2AAsyncV2Resp CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.T2AAsyncV2Resp();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base_resp", n => { BaseResp = n.GetObjectValue<global::MiniMax.Models.BaseResp>(global::MiniMax.Models.BaseResp.CreateFromDiscriminatorValue); } },
                { "file_id", n => { FileId = n.GetLongValue(); } },
                { "task_id", n => { TaskId = n.GetStringValue(); } },
                { "task_token", n => { TaskToken = n.GetStringValue(); } },
                { "usage_characters", n => { UsageCharacters = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MiniMax.Models.BaseResp>("base_resp", BaseResp);
            writer.WriteLongValue("file_id", FileId);
            writer.WriteStringValue("task_id", TaskId);
            writer.WriteStringValue("task_token", TaskToken);
            writer.WriteIntValue("usage_characters", UsageCharacters);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
