// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class T2AAudioSetting : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>生成音频的比特率。可选范围`[32000，64000，128000，256000]`，默认值为 `128000`。该参数仅对 `mp3` 格式的音频生效</summary>
        public long? Bitrate { get; set; }
        /// <summary>生成音频的声道数。可选范围：`[1,2]`，其中 `1` 为单声道，`2` 为双声道，默认值为 1</summary>
        public long? Channel { get; set; }
        /// <summary>对于音频恒定比特率（cbr）控制，可选 `false`、 `true`。当此参数设置为 `true`，将以恒定比特率方式进行音频编码。注意：本参数仅当音频设置为**流式**输出，且音频格式为 `mp3` 时生效。</summary>
        public bool? ForceCbr { get; set; }
        /// <summary>生成音频的格式，`wav` 仅在非流式输出下支持</summary>
        public global::MiniMax.Models.T2AAudioSetting_format? Format { get; set; }
        /// <summary>生成音频的采样率。可选范围`[8000，16000，22050，24000，32000，44100]`，默认为 `32000`</summary>
        public long? SampleRate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.T2AAudioSetting"/> and sets the default values.
        /// </summary>
        public T2AAudioSetting()
        {
            AdditionalData = new Dictionary<string, object>();
            Format = global::MiniMax.Models.T2AAudioSetting_format.Mp3;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.T2AAudioSetting"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.T2AAudioSetting CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.T2AAudioSetting();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bitrate", n => { Bitrate = n.GetLongValue(); } },
                { "channel", n => { Channel = n.GetLongValue(); } },
                { "force_cbr", n => { ForceCbr = n.GetBoolValue(); } },
                { "format", n => { Format = n.GetEnumValue<global::MiniMax.Models.T2AAudioSetting_format>(); } },
                { "sample_rate", n => { SampleRate = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("bitrate", Bitrate);
            writer.WriteLongValue("channel", Channel);
            writer.WriteBoolValue("force_cbr", ForceCbr);
            writer.WriteEnumValue<global::MiniMax.Models.T2AAudioSetting_format>("format", Format);
            writer.WriteLongValue("sample_rate", SampleRate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
