// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>是否增强对指定的小语种和方言的识别能力。默认值为 `null`，可设置为 `auto` 让模型自主判断。注意：speech-01 和 speech-02 系列模型暂不支持 Persian、Filipino、Tamil 这三个语种。</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum T2AAsyncV2Req_language_boost
    {
        [EnumMember(Value = "Chinese")]
        #pragma warning disable CS1591
        Chinese,
        #pragma warning restore CS1591
        [EnumMember(Value = "Chinese,Yue")]
        #pragma warning disable CS1591
        ChineseYue,
        #pragma warning restore CS1591
        [EnumMember(Value = "English")]
        #pragma warning disable CS1591
        English,
        #pragma warning restore CS1591
        [EnumMember(Value = "Arabic")]
        #pragma warning disable CS1591
        Arabic,
        #pragma warning restore CS1591
        [EnumMember(Value = "Russian")]
        #pragma warning disable CS1591
        Russian,
        #pragma warning restore CS1591
        [EnumMember(Value = "Spanish")]
        #pragma warning disable CS1591
        Spanish,
        #pragma warning restore CS1591
        [EnumMember(Value = "French")]
        #pragma warning disable CS1591
        French,
        #pragma warning restore CS1591
        [EnumMember(Value = "Portuguese")]
        #pragma warning disable CS1591
        Portuguese,
        #pragma warning restore CS1591
        [EnumMember(Value = "German")]
        #pragma warning disable CS1591
        German,
        #pragma warning restore CS1591
        [EnumMember(Value = "Turkish")]
        #pragma warning disable CS1591
        Turkish,
        #pragma warning restore CS1591
        [EnumMember(Value = "Dutch")]
        #pragma warning disable CS1591
        Dutch,
        #pragma warning restore CS1591
        [EnumMember(Value = "Ukrainian")]
        #pragma warning disable CS1591
        Ukrainian,
        #pragma warning restore CS1591
        [EnumMember(Value = "Vietnamese")]
        #pragma warning disable CS1591
        Vietnamese,
        #pragma warning restore CS1591
        [EnumMember(Value = "Indonesian")]
        #pragma warning disable CS1591
        Indonesian,
        #pragma warning restore CS1591
        [EnumMember(Value = "Japanese")]
        #pragma warning disable CS1591
        Japanese,
        #pragma warning restore CS1591
        [EnumMember(Value = "Italian")]
        #pragma warning disable CS1591
        Italian,
        #pragma warning restore CS1591
        [EnumMember(Value = "Korean")]
        #pragma warning disable CS1591
        Korean,
        #pragma warning restore CS1591
        [EnumMember(Value = "Thai")]
        #pragma warning disable CS1591
        Thai,
        #pragma warning restore CS1591
        [EnumMember(Value = "Polish")]
        #pragma warning disable CS1591
        Polish,
        #pragma warning restore CS1591
        [EnumMember(Value = "Romanian")]
        #pragma warning disable CS1591
        Romanian,
        #pragma warning restore CS1591
        [EnumMember(Value = "Greek")]
        #pragma warning disable CS1591
        Greek,
        #pragma warning restore CS1591
        [EnumMember(Value = "Czech")]
        #pragma warning disable CS1591
        Czech,
        #pragma warning restore CS1591
        [EnumMember(Value = "Finnish")]
        #pragma warning disable CS1591
        Finnish,
        #pragma warning restore CS1591
        [EnumMember(Value = "Hindi")]
        #pragma warning disable CS1591
        Hindi,
        #pragma warning restore CS1591
        [EnumMember(Value = "Bulgarian")]
        #pragma warning disable CS1591
        Bulgarian,
        #pragma warning restore CS1591
        [EnumMember(Value = "Danish")]
        #pragma warning disable CS1591
        Danish,
        #pragma warning restore CS1591
        [EnumMember(Value = "Hebrew")]
        #pragma warning disable CS1591
        Hebrew,
        #pragma warning restore CS1591
        [EnumMember(Value = "Malay")]
        #pragma warning disable CS1591
        Malay,
        #pragma warning restore CS1591
        [EnumMember(Value = "Persian")]
        #pragma warning disable CS1591
        Persian,
        #pragma warning restore CS1591
        [EnumMember(Value = "Slovak")]
        #pragma warning disable CS1591
        Slovak,
        #pragma warning restore CS1591
        [EnumMember(Value = "Swedish")]
        #pragma warning disable CS1591
        Swedish,
        #pragma warning restore CS1591
        [EnumMember(Value = "Croatian")]
        #pragma warning disable CS1591
        Croatian,
        #pragma warning restore CS1591
        [EnumMember(Value = "Filipino")]
        #pragma warning disable CS1591
        Filipino,
        #pragma warning restore CS1591
        [EnumMember(Value = "Hungarian")]
        #pragma warning disable CS1591
        Hungarian,
        #pragma warning restore CS1591
        [EnumMember(Value = "Norwegian")]
        #pragma warning disable CS1591
        Norwegian,
        #pragma warning restore CS1591
        [EnumMember(Value = "Slovenian")]
        #pragma warning disable CS1591
        Slovenian,
        #pragma warning restore CS1591
        [EnumMember(Value = "Catalan")]
        #pragma warning disable CS1591
        Catalan,
        #pragma warning restore CS1591
        [EnumMember(Value = "Nynorsk")]
        #pragma warning disable CS1591
        Nynorsk,
        #pragma warning restore CS1591
        [EnumMember(Value = "Tamil")]
        #pragma warning disable CS1591
        Tamil,
        #pragma warning restore CS1591
        [EnumMember(Value = "Afrikaans")]
        #pragma warning disable CS1591
        Afrikaans,
        #pragma warning restore CS1591
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
    }
}
