// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>控制输出结果形式的参数，可选值范围为[`url`, `hex`]，默认值为 `hex` 。该参数仅在非流式场景生效，流式场景仅支持返回 hex 形式。返回的 url 有效期为 24 小时</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum T2aV2Req_output_format
    {
        [EnumMember(Value = "url")]
        #pragma warning disable CS1591
        Url,
        #pragma warning restore CS1591
        [EnumMember(Value = "hex")]
        #pragma warning disable CS1591
        Hex,
        #pragma warning restore CS1591
    }
}
