// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class T2aV2Resp : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>本次请求的状态码和详情</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.T2aV2Resp_base_resp? BaseResp { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.T2aV2Resp_base_resp BaseResp { get; set; }
#endif
        /// <summary>返回的合成数据对象，可能为 null，需进行非空判断</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.T2aV2Resp_data? Data { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.T2aV2Resp_data Data { get; set; }
#endif
        /// <summary>音频的附加信息</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.T2aV2Resp_extra_info? ExtraInfo { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.T2aV2Resp_extra_info ExtraInfo { get; set; }
#endif
        /// <summary>本次会话的 id，用于在咨询/反馈时帮助定位问题</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TraceId { get; set; }
#nullable restore
#else
        public string TraceId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.T2aV2Resp"/> and sets the default values.
        /// </summary>
        public T2aV2Resp()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.T2aV2Resp"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.T2aV2Resp CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.T2aV2Resp();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base_resp", n => { BaseResp = n.GetObjectValue<global::MiniMax.Models.T2aV2Resp_base_resp>(global::MiniMax.Models.T2aV2Resp_base_resp.CreateFromDiscriminatorValue); } },
                { "data", n => { Data = n.GetObjectValue<global::MiniMax.Models.T2aV2Resp_data>(global::MiniMax.Models.T2aV2Resp_data.CreateFromDiscriminatorValue); } },
                { "extra_info", n => { ExtraInfo = n.GetObjectValue<global::MiniMax.Models.T2aV2Resp_extra_info>(global::MiniMax.Models.T2aV2Resp_extra_info.CreateFromDiscriminatorValue); } },
                { "trace_id", n => { TraceId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MiniMax.Models.T2aV2Resp_base_resp>("base_resp", BaseResp);
            writer.WriteObjectValue<global::MiniMax.Models.T2aV2Resp_data>("data", Data);
            writer.WriteObjectValue<global::MiniMax.Models.T2aV2Resp_extra_info>("extra_info", ExtraInfo);
            writer.WriteStringValue("trace_id", TraceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
