// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    /// <summary>
    /// 音频的附加信息
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class T2aV2Resp_extra_info : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>生成音频声道数,1：单声道，2：双声道</summary>
        public long? AudioChannel { get; set; }
        /// <summary>生成音频文件的格式。取值范围 `[mp3, pcm, flac]`</summary>
        public global::MiniMax.Models.T2aV2Resp_extra_info_audio_format? AudioFormat { get; set; }
        /// <summary>音频时长（毫秒）</summary>
        public long? AudioLength { get; set; }
        /// <summary>音频采样率</summary>
        public long? AudioSampleRate { get; set; }
        /// <summary>音频文件大小（字节）</summary>
        public long? AudioSize { get; set; }
        /// <summary>音频比特率</summary>
        public long? Bitrate { get; set; }
        /// <summary>非法字符占比.非法字符不超过 10%（包含 10%），音频会正常生成,并返回非法字符占比数据；如超过 10% 将进行报错</summary>
        public float? InvisibleCharacterRatio { get; set; }
        /// <summary>计费字符数</summary>
        public long? UsageCharacters { get; set; }
        /// <summary>已发音的字数统计，包含汉字、数字、字母，不包含标点符号</summary>
        public long? WordCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.T2aV2Resp_extra_info"/> and sets the default values.
        /// </summary>
        public T2aV2Resp_extra_info()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.T2aV2Resp_extra_info"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.T2aV2Resp_extra_info CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.T2aV2Resp_extra_info();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audio_channel", n => { AudioChannel = n.GetLongValue(); } },
                { "audio_format", n => { AudioFormat = n.GetEnumValue<global::MiniMax.Models.T2aV2Resp_extra_info_audio_format>(); } },
                { "audio_length", n => { AudioLength = n.GetLongValue(); } },
                { "audio_sample_rate", n => { AudioSampleRate = n.GetLongValue(); } },
                { "audio_size", n => { AudioSize = n.GetLongValue(); } },
                { "bitrate", n => { Bitrate = n.GetLongValue(); } },
                { "invisible_character_ratio", n => { InvisibleCharacterRatio = n.GetFloatValue(); } },
                { "usage_characters", n => { UsageCharacters = n.GetLongValue(); } },
                { "word_count", n => { WordCount = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("audio_channel", AudioChannel);
            writer.WriteEnumValue<global::MiniMax.Models.T2aV2Resp_extra_info_audio_format>("audio_format", AudioFormat);
            writer.WriteLongValue("audio_length", AudioLength);
            writer.WriteLongValue("audio_sample_rate", AudioSampleRate);
            writer.WriteLongValue("audio_size", AudioSize);
            writer.WriteLongValue("bitrate", Bitrate);
            writer.WriteFloatValue("invisible_character_ratio", InvisibleCharacterRatio);
            writer.WriteLongValue("usage_characters", UsageCharacters);
            writer.WriteLongValue("word_count", WordCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
