// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class T2aV2Req : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>控制在合成音频的末尾添加音频节奏标识，默认值为 False。该参数仅对非流式合成生效</summary>
        public bool? AigcWatermark { get; set; }
        /// <summary>The audio_setting property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.T2AAudioSetting? AudioSetting { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.T2AAudioSetting AudioSetting { get; set; }
#endif
        /// <summary>是否增强对指定的小语种和方言的识别能力。默认值为 `null`，可设置为 `auto` 让模型自主判断。注意：speech-01 和 speech-02 系列模型暂不支持 Persian、Filipino、Tamil 这三个语种。</summary>
        public global::MiniMax.Models.T2aV2Req_language_boost? LanguageBoost { get; set; }
        /// <summary>请求的模型版本，可选范围：`speech-2.8-hd`, `speech-2.8-turbo`, `speech-2.6-hd`, `speech-2.6-turbo`, `speech-02-hd`, `speech-02-turbo`, `speech-01-hd`, `speech-01-turbo`.</summary>
        public global::MiniMax.Models.T2aV2Req_model? Model { get; set; }
        /// <summary>控制输出结果形式的参数，可选值范围为[`url`, `hex`]，默认值为 `hex` 。该参数仅在非流式场景生效，流式场景仅支持返回 hex 形式。返回的 url 有效期为 24 小时</summary>
        public global::MiniMax.Models.T2aV2Req_output_format? OutputFormat { get; set; }
        /// <summary>The pronunciation_dict property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.PronunciationDict? PronunciationDict { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.PronunciationDict PronunciationDict { get; set; }
#endif
        /// <summary>控制是否流式输出。默认 false，即不开启流式</summary>
        public bool? Stream { get; set; }
        /// <summary>The stream_options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.T2AStreamOption? StreamOptions { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.T2AStreamOption StreamOptions { get; set; }
#endif
        /// <summary>控制是否开启字幕服务，默认值为 false。仅对 `speech-2.8-hd`, `speech-2.8-turbo`, `speech-2.6-hd`, `speech-2.6-turbo`, `speech-02-hd`, `speech-02-turbo`, `speech-01-hd`, `speech-01-turbo` 模型有效</summary>
        public bool? SubtitleEnable { get; set; }
        /// <summary>需要合成语音的文本，长度限制小于 10000 字符，若文本长度大于 3000 字符，推荐使用流式输出- 段落切换用换行符标记- 停顿控制：支持自定义文本之间的语音时间间隔，以实现自定义文本语音停顿时间的效果。使用方式：在文本中增加`&lt;#x#&gt;`标记，`x` 为停顿时长（单位：秒），范围 [0.01, 99.99]，最多保留两位小数。文本间隔时间需设置在两个可以语音发音的文本之间，不可连续使用多个停顿标记- 语气词标签：仅当模型选择 `speech-2.8-hd` 或 `speech-2.8-turbo` 时，支持在文本中插入语气词标签。支持的语气词：`(laughs)`（笑声）、`(chuckle)`（轻笑）、`(coughs)`（咳嗽）、`(clear-throat)`（清嗓子）、`(groans)`（呻吟）、`(breath)`（正常换气）、`(pant)`（喘气）、`(inhale)`（吸气）、`(exhale)`（呼气）、`(gasps)`（倒吸气）、`(sniffs)`（吸鼻子）、`(sighs)`（叹气）、`(snorts)`（喷鼻息）、`(burps)`（打嗝）、`(lip-smacking)`（咂嘴）、`(humming)`（哼唱）、`(hissing)`（嘶嘶声）、`(emm)`（嗯）、`(sneezes)`（喷嚏）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The timbre_weights property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MiniMax.Models.TimbreWeights>? TimbreWeights { get; set; }
#nullable restore
#else
        public List<global::MiniMax.Models.TimbreWeights> TimbreWeights { get; set; }
#endif
        /// <summary>声音效果器设置</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.VoiceModify? VoiceModify { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.VoiceModify VoiceModify { get; set; }
#endif
        /// <summary>The voice_setting property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.T2AVoiceSetting? VoiceSetting { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.T2AVoiceSetting VoiceSetting { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.T2aV2Req"/> and sets the default values.
        /// </summary>
        public T2aV2Req()
        {
            AdditionalData = new Dictionary<string, object>();
            OutputFormat = global::MiniMax.Models.T2aV2Req_output_format.Hex;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.T2aV2Req"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.T2aV2Req CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.T2aV2Req();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aigc_watermark", n => { AigcWatermark = n.GetBoolValue(); } },
                { "audio_setting", n => { AudioSetting = n.GetObjectValue<global::MiniMax.Models.T2AAudioSetting>(global::MiniMax.Models.T2AAudioSetting.CreateFromDiscriminatorValue); } },
                { "language_boost", n => { LanguageBoost = n.GetEnumValue<global::MiniMax.Models.T2aV2Req_language_boost>(); } },
                { "model", n => { Model = n.GetEnumValue<global::MiniMax.Models.T2aV2Req_model>(); } },
                { "output_format", n => { OutputFormat = n.GetEnumValue<global::MiniMax.Models.T2aV2Req_output_format>(); } },
                { "pronunciation_dict", n => { PronunciationDict = n.GetObjectValue<global::MiniMax.Models.PronunciationDict>(global::MiniMax.Models.PronunciationDict.CreateFromDiscriminatorValue); } },
                { "stream", n => { Stream = n.GetBoolValue(); } },
                { "stream_options", n => { StreamOptions = n.GetObjectValue<global::MiniMax.Models.T2AStreamOption>(global::MiniMax.Models.T2AStreamOption.CreateFromDiscriminatorValue); } },
                { "subtitle_enable", n => { SubtitleEnable = n.GetBoolValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "timbre_weights", n => { TimbreWeights = n.GetCollectionOfObjectValues<global::MiniMax.Models.TimbreWeights>(global::MiniMax.Models.TimbreWeights.CreateFromDiscriminatorValue)?.AsList(); } },
                { "voice_modify", n => { VoiceModify = n.GetObjectValue<global::MiniMax.Models.VoiceModify>(global::MiniMax.Models.VoiceModify.CreateFromDiscriminatorValue); } },
                { "voice_setting", n => { VoiceSetting = n.GetObjectValue<global::MiniMax.Models.T2AVoiceSetting>(global::MiniMax.Models.T2AVoiceSetting.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("aigc_watermark", AigcWatermark);
            writer.WriteObjectValue<global::MiniMax.Models.T2AAudioSetting>("audio_setting", AudioSetting);
            writer.WriteEnumValue<global::MiniMax.Models.T2aV2Req_language_boost>("language_boost", LanguageBoost);
            writer.WriteEnumValue<global::MiniMax.Models.T2aV2Req_model>("model", Model);
            writer.WriteEnumValue<global::MiniMax.Models.T2aV2Req_output_format>("output_format", OutputFormat);
            writer.WriteObjectValue<global::MiniMax.Models.PronunciationDict>("pronunciation_dict", PronunciationDict);
            writer.WriteBoolValue("stream", Stream);
            writer.WriteObjectValue<global::MiniMax.Models.T2AStreamOption>("stream_options", StreamOptions);
            writer.WriteBoolValue("subtitle_enable", SubtitleEnable);
            writer.WriteStringValue("text", Text);
            writer.WriteCollectionOfObjectValues<global::MiniMax.Models.TimbreWeights>("timbre_weights", TimbreWeights);
            writer.WriteObjectValue<global::MiniMax.Models.VoiceModify>("voice_modify", VoiceModify);
            writer.WriteObjectValue<global::MiniMax.Models.T2AVoiceSetting>("voice_setting", VoiceSetting);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
