// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VideoGenerationReq : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>是否在生成的视频中添加水印，默认为 `false`</summary>
        public bool? AigcWatermark { get; set; }
        /// <summary>接收任务状态更新通知的回调 URL。支持配置回调地址，验证通过后当任务状态变更时会推送最新状态。状态包括：processing（生成中）、success（成功）、failed（失败）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallbackUrl { get; set; }
#nullable restore
#else
        public string CallbackUrl { get; set; }
#endif
        /// <summary>视频时长（秒），默认值为 6。其可用值与模型和分辨率相关：| Model |  720P |768P | 1080P || :--- |:--- |:--- | :--- || MiniMax-Hailuo-2.3 | - | `6` 或 `10` | `6` || MiniMax-Hailuo-02 | - | `6` 或 `10` | `6` || 其他模型 | `6` | - |`6` |  </summary>
        public int? Duration { get; set; }
        /// <summary>是否缩短 `prompt_optimizer` 的优化耗时，默认为 false。仅对 `MiniMax-Hailuo-2.3` 和 `MiniMax-Hailuo-02` 模型生效。</summary>
        public bool? FastPretreatment { get; set; }
        /// <summary>模型名称。可用值： `MiniMax-Hailuo-2.3`, `MiniMax-Hailuo-02`, `T2V-01-Director`, `T2V-01`.</summary>
        public global::MiniMax.Models.VideoGenerationReq_model? Model { get; set; }
        /// <summary>视频的文本描述，最大 2000 字符。对于 `MiniMax-Hailuo-2.3`、`MiniMax-Hailuo-02` 和 `*-Director` 系列模型，支持使用 `[指令]` 语法进行运镜控制。可在 prompt 中通过 [指令] 格式添加运镜指令，以实现精确的镜头控制。- 支持 15 种运镜指令的指令: - 左右移: [左移], [右移] - 左右摇: [左摇], [右摇] - 推拉: [推进], [拉远] - 升降: [上升], [下降] - 上下摇: [上摇], [下摇] - 变焦: [变焦推近], [变焦拉远] - 其他: [晃动], [跟随], [固定] - 使用规则: - 组合运镜: 同一组 [] 内的多个指令会同时生效，如 [左摇,上升]，建议组合不超过 3 个 - 顺序运镜: prompt 中前后出现的指令会依次生效，如 &quot;...[推进], 然后...[拉远]&quot; - 自然语言: 也支持通过自然语言描述运镜，但使用标准指令能获得更准确的响应 </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>是否自动优化 `prompt`，默认为 `true`。设为 `false` 可进行更精确的控制</summary>
        public bool? PromptOptimizer { get; set; }
        /// <summary>视频分辨率。其可用值与模型相关：| Model | 6s | 10s || :--- | :--- | :--- || MiniMax-Hailuo-2.3 |  `768P` (默认), `1080P` |  `768P` (默认) || MiniMax-Hailuo-02 |  `768P` (默认), `1080P` |  `768P` (默认) || 其他模型 | `720P` (默认) | 不支持 |</summary>
        public global::MiniMax.Models.VideoGenerationReq_resolution? Resolution { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.VideoGenerationReq"/> and sets the default values.
        /// </summary>
        public VideoGenerationReq()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.VideoGenerationReq"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.VideoGenerationReq CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.VideoGenerationReq();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aigc_watermark", n => { AigcWatermark = n.GetBoolValue(); } },
                { "callback_url", n => { CallbackUrl = n.GetStringValue(); } },
                { "duration", n => { Duration = n.GetIntValue(); } },
                { "fast_pretreatment", n => { FastPretreatment = n.GetBoolValue(); } },
                { "model", n => { Model = n.GetEnumValue<global::MiniMax.Models.VideoGenerationReq_model>(); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "prompt_optimizer", n => { PromptOptimizer = n.GetBoolValue(); } },
                { "resolution", n => { Resolution = n.GetEnumValue<global::MiniMax.Models.VideoGenerationReq_resolution>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("aigc_watermark", AigcWatermark);
            writer.WriteStringValue("callback_url", CallbackUrl);
            writer.WriteIntValue("duration", Duration);
            writer.WriteBoolValue("fast_pretreatment", FastPretreatment);
            writer.WriteEnumValue<global::MiniMax.Models.VideoGenerationReq_model>("model", Model);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteBoolValue("prompt_optimizer", PromptOptimizer);
            writer.WriteEnumValue<global::MiniMax.Models.VideoGenerationReq_resolution>("resolution", Resolution);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
