// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>任务的当前状态。可能的状态值包括：- `Preparing` – 准备中- `Queueing` – 队列中- `Processing` – 生成中- `Success` – 成功- `Fail` – 失败</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VideoProcessStatus
    {
        [EnumMember(Value = "Preparing")]
        #pragma warning disable CS1591
        Preparing,
        #pragma warning restore CS1591
        [EnumMember(Value = "Queueing")]
        #pragma warning disable CS1591
        Queueing,
        #pragma warning restore CS1591
        [EnumMember(Value = "Processing")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
        [EnumMember(Value = "Success")]
        #pragma warning disable CS1591
        Success,
        #pragma warning restore CS1591
        [EnumMember(Value = "Fail")]
        #pragma warning disable CS1591
        Fail,
        #pragma warning restore CS1591
    }
}
