// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>视频分辨率。其可用值与模型相关：| Model | 6s | 10s || :--- | :--- | :--- || MiniMax-Hailuo-2.3 |  `768P` (默认), `1080P` |  `768P` (默认) || MiniMax-Hailuo-02 |  `768P` (默认), `1080P` |  `768P` (默认) || 其他模型 | `720P` (默认) | 不支持 |</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VideoGenerationReq_resolution
    {
        [EnumMember(Value = "720P")]
        #pragma warning disable CS1591
        SevenTwoZeroP,
        #pragma warning restore CS1591
        [EnumMember(Value = "768P")]
        #pragma warning disable CS1591
        SevenSixEightP,
        #pragma warning restore CS1591
        [EnumMember(Value = "1080P")]
        #pragma warning disable CS1591
        OneZeroEightZeroP,
        #pragma warning restore CS1591
    }
}
