// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>模型名称。可用值： `MiniMax-Hailuo-2.3`, `MiniMax-Hailuo-02`, `T2V-01-Director`, `T2V-01`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VideoGenerationReq_model
    {
        [EnumMember(Value = "MiniMax-Hailuo-2.3")]
        #pragma warning disable CS1591
        MiniMaxHailuo23,
        #pragma warning restore CS1591
        [EnumMember(Value = "MiniMax-Hailuo-02")]
        #pragma warning disable CS1591
        MiniMaxHailuo02,
        #pragma warning restore CS1591
        [EnumMember(Value = "T2V-01-Director")]
        #pragma warning disable CS1591
        T2V01Director,
        #pragma warning restore CS1591
        [EnumMember(Value = "T2V-01")]
        #pragma warning disable CS1591
        T2V01,
        #pragma warning restore CS1591
    }
}
