// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VoiceCloneBaseResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>状态码- 0: 请求结果正常- 1000：未知错误- 1001：超时- 1002：触发限流- 1004：鉴权失败- 1013：服务内部错误- 2013：输入格式信息不正常- 2038：无复刻权限，请检查账号认证状态更多内容可查看[错误码查询列表](/api-reference/errorcode)了解详情</summary>
        public long? StatusCode { get; set; }
        /// <summary>状态详情</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusMsg { get; set; }
#nullable restore
#else
        public string StatusMsg { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.VoiceCloneBaseResponse"/> and sets the default values.
        /// </summary>
        public VoiceCloneBaseResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.VoiceCloneBaseResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.VoiceCloneBaseResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.VoiceCloneBaseResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "status_code", n => { StatusCode = n.GetLongValue(); } },
                { "status_msg", n => { StatusMsg = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("status_code", StatusCode);
            writer.WriteStringValue("status_msg", StatusMsg);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
