// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VoiceCloneResp : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The base_resp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.VoiceCloneBaseResponse? BaseResp { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.VoiceCloneBaseResponse BaseResp { get; set; }
#endif
        /// <summary>如果请求体中传入了试听文本 text 以及合成试听音频的模型 model，那么本参数将以链接形式返回试听音频，否则本参数为空值</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DemoAudio { get; set; }
#nullable restore
#else
        public string DemoAudio { get; set; }
#endif
        /// <summary>输入音频是否命中风控</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.VoiceCloneResp_input_sensitive? InputSensitive { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.VoiceCloneResp_input_sensitive InputSensitive { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.VoiceCloneResp"/> and sets the default values.
        /// </summary>
        public VoiceCloneResp()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.VoiceCloneResp"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.VoiceCloneResp CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.VoiceCloneResp();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base_resp", n => { BaseResp = n.GetObjectValue<global::MiniMax.Models.VoiceCloneBaseResponse>(global::MiniMax.Models.VoiceCloneBaseResponse.CreateFromDiscriminatorValue); } },
                { "demo_audio", n => { DemoAudio = n.GetStringValue(); } },
                { "input_sensitive", n => { InputSensitive = n.GetObjectValue<global::MiniMax.Models.VoiceCloneResp_input_sensitive>(global::MiniMax.Models.VoiceCloneResp_input_sensitive.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MiniMax.Models.VoiceCloneBaseResponse>("base_resp", BaseResp);
            writer.WriteStringValue("demo_audio", DemoAudio);
            writer.WriteObjectValue<global::MiniMax.Models.VoiceCloneResp_input_sensitive>("input_sensitive", InputSensitive);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
