// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>音效设置，单次仅能选择一种，可选值：1. spacious_echo（空旷回音）2. auditorium_echo（礼堂广播）3. lofi_telephone（电话失真）4. robotic（电音）</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VoiceModify_sound_effects
    {
        [EnumMember(Value = "spacious_echo")]
        #pragma warning disable CS1591
        Spacious_echo,
        #pragma warning restore CS1591
        [EnumMember(Value = "auditorium_echo")]
        #pragma warning disable CS1591
        Auditorium_echo,
        #pragma warning restore CS1591
        [EnumMember(Value = "lofi_telephone")]
        #pragma warning disable CS1591
        Lofi_telephone,
        #pragma warning restore CS1591
        [EnumMember(Value = "robotic")]
        #pragma warning disable CS1591
        Robotic,
        #pragma warning restore CS1591
    }
}
