// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    /// <summary>
    /// 声音效果器设置
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VoiceModify : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>强度调整（力量感/柔和），范围 [-100,100]，数值接近 -100，声音更刚劲；接近 100，声音更轻柔![intensity adjustment](https://filecdn.minimax.chat/public/862d493e-71d5-4d1f-b7c3-9ac51890631b.png)</summary>
        public int? Intensity { get; set; }
        /// <summary>音高调整（低沉/明亮），范围 [-100,100]，数值接近 -100，声音更低沉；接近 100，声音更明亮![pitch adjustment](https://filecdn.minimax.chat/public/5d210c47-4236-4e81-893b-16cc1ef0302d.png)</summary>
        public int? Pitch { get; set; }
        /// <summary>音效设置，单次仅能选择一种，可选值：1. spacious_echo（空旷回音）2. auditorium_echo（礼堂广播）3. lofi_telephone（电话失真）4. robotic（电音）</summary>
        public global::MiniMax.Models.VoiceModify_sound_effects? SoundEffects { get; set; }
        /// <summary>音色调整（磁性/清脆），范围 [-100,100]，数值接近 -100，声音更浑厚；数值接近 100，声音更清脆![timbre adjustment](https://filecdn.minimax.chat/public/5f0e6cae-363a-452b-8d42-fbc4ef5a0510.png)</summary>
        public int? Timbre { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.VoiceModify"/> and sets the default values.
        /// </summary>
        public VoiceModify()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.VoiceModify"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.VoiceModify CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.VoiceModify();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "intensity", n => { Intensity = n.GetIntValue(); } },
                { "pitch", n => { Pitch = n.GetIntValue(); } },
                { "sound_effects", n => { SoundEffects = n.GetEnumValue<global::MiniMax.Models.VoiceModify_sound_effects>(); } },
                { "timbre", n => { Timbre = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("intensity", Intensity);
            writer.WriteIntValue("pitch", Pitch);
            writer.WriteEnumValue<global::MiniMax.Models.VoiceModify_sound_effects>("sound_effects", SoundEffects);
            writer.WriteIntValue("timbre", Timbre);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
