// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MiniMax.Models
{
    /// <summary>复刻试听参数。指定合成试听音频使用的语音模型，提供 `text` 字段时必传此字段。可选项：</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VoiceCloneReq_model
    {
        [EnumMember(Value = "speech-2.8-hd")]
        #pragma warning disable CS1591
        Speech28Hd,
        #pragma warning restore CS1591
        [EnumMember(Value = "speech-2.8-turbo")]
        #pragma warning disable CS1591
        Speech28Turbo,
        #pragma warning restore CS1591
        [EnumMember(Value = "speech-2.6-hd")]
        #pragma warning disable CS1591
        Speech26Hd,
        #pragma warning restore CS1591
        [EnumMember(Value = "speech-2.6-turbo")]
        #pragma warning disable CS1591
        Speech26Turbo,
        #pragma warning restore CS1591
        [EnumMember(Value = "speech-02-hd")]
        #pragma warning disable CS1591
        Speech02Hd,
        #pragma warning restore CS1591
        [EnumMember(Value = "speech-02-turbo")]
        #pragma warning disable CS1591
        Speech02Turbo,
        #pragma warning restore CS1591
        [EnumMember(Value = "speech-01-hd")]
        #pragma warning disable CS1591
        Speech01Hd,
        #pragma warning restore CS1591
        [EnumMember(Value = "speech-01-turbo")]
        #pragma warning disable CS1591
        Speech01Turbo,
        #pragma warning restore CS1591
    }
}
