// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MiniMax.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VoiceCloneReq : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>是否在合成试听音频的末尾添加音频节奏标识，默认值为 false</summary>
        public bool? AigcWatermark { get; set; }
        /// <summary>音色复刻示例音频，提供本参数将有助于增强语音合成的音色相似度和稳定性。若使用本参数，需同时上传一小段示例音频上传的音频文件需遵从以下规范：- 上传的音频文件格式需为：mp3、m4a、wav 格式- 上传的音频文件的时长小于 8 秒- 上传的音频文件大小需不超过 20 mb</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MiniMax.Models.ClonePrompt? ClonePrompt { get; set; }
#nullable restore
#else
        public global::MiniMax.Models.ClonePrompt ClonePrompt { get; set; }
#endif
        /// <summary>待复刻音频的 file_id，通过[文件上传接口](/api-reference/file-management-upload)获得上传的待复刻音频文件需遵从以下规范：- 上传的音频文件格式需为：mp3、m4a、wav 格式- 上传的音频文件的时长最少应不低于 10 秒，最长应不超过 5 分钟- 上传的音频文件大小需不超过 20 mb- 若使用该参数，则两个子属性（prompt_audio、prompt_text）都为必填项</summary>
        public long? FileId { get; set; }
        /// <summary>是否增强对指定的小语种和方言的识别能力。默认值为 null，可设置为 `auto` 让模型自主判断。</summary>
        public global::MiniMax.Models.VoiceCloneReq_language_boost? LanguageBoost { get; set; }
        /// <summary>复刻试听参数。指定合成试听音频使用的语音模型，提供 `text` 字段时必传此字段。可选项：</summary>
        public global::MiniMax.Models.VoiceCloneReq_model? Model { get; set; }
        /// <summary>音频复刻参数，表示是否开启降噪，默认值为 false</summary>
        public bool? NeedNoiseReduction { get; set; }
        /// <summary>音频复刻参数，是否开启音量归一化，默认值为 false</summary>
        public bool? NeedVolumeNormalization { get; set; }
        /// <summary>复刻试听参数，限制 1000 字符以内。模型将使用复刻后的音色朗读本段文本内容，并返回试听音频链接。 注：试听将根据字符数正常收取语音合成费用，定价与 T2A 各接口一致- 语气词标签：仅当模型选择 `speech-2.8-hd` 或 `speech-2.8-turbo` 时，支持在文本中插入语气词标签。支持的语气词：`(laughs)`（笑声）、`(chuckle)`（轻笑）、`(coughs)`（咳嗽）、`(clear-throat)`（清嗓子）、`(groans)`（呻吟）、`(breath)`（正常换气）、`(pant)`（喘气）、`(inhale)`（吸气）、`(exhale)`（呼气）、`(gasps)`（倒吸气）、`(sniffs)`（吸鼻子）、`(sighs)`（叹气）、`(snorts)`（喷鼻息）、`(burps)`（打嗝）、`(lip-smacking)`（咂嘴）、`(humming)`（哼唱）、`(hissing)`（嘶嘶声）、`(emm)`（嗯）、`(whistles)`（口哨）、`(sneezes)`（喷嚏）、`(crying)`（抽泣）、`(applause)`（鼓掌）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>克隆音色的 voice_id，正确示例：&quot;MiniMax001&quot;。用户进行自定义 voice_id 时需注意：- 自定义的 voice_id 长度范围[8,256]- 首字符必须为英文字母- 允许数字、字母、-、_- 末位字符不可为 -、_- voice_id 不可与已有 id 重复，否则会报错</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VoiceId { get; set; }
#nullable restore
#else
        public string VoiceId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MiniMax.Models.VoiceCloneReq"/> and sets the default values.
        /// </summary>
        public VoiceCloneReq()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MiniMax.Models.VoiceCloneReq"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MiniMax.Models.VoiceCloneReq CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MiniMax.Models.VoiceCloneReq();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aigc_watermark", n => { AigcWatermark = n.GetBoolValue(); } },
                { "clone_prompt", n => { ClonePrompt = n.GetObjectValue<global::MiniMax.Models.ClonePrompt>(global::MiniMax.Models.ClonePrompt.CreateFromDiscriminatorValue); } },
                { "file_id", n => { FileId = n.GetLongValue(); } },
                { "language_boost", n => { LanguageBoost = n.GetEnumValue<global::MiniMax.Models.VoiceCloneReq_language_boost>(); } },
                { "model", n => { Model = n.GetEnumValue<global::MiniMax.Models.VoiceCloneReq_model>(); } },
                { "need_noise_reduction", n => { NeedNoiseReduction = n.GetBoolValue(); } },
                { "need_volume_normalization", n => { NeedVolumeNormalization = n.GetBoolValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "voice_id", n => { VoiceId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("aigc_watermark", AigcWatermark);
            writer.WriteObjectValue<global::MiniMax.Models.ClonePrompt>("clone_prompt", ClonePrompt);
            writer.WriteLongValue("file_id", FileId);
            writer.WriteEnumValue<global::MiniMax.Models.VoiceCloneReq_language_boost>("language_boost", LanguageBoost);
            writer.WriteEnumValue<global::MiniMax.Models.VoiceCloneReq_model>("model", Model);
            writer.WriteBoolValue("need_noise_reduction", NeedNoiseReduction);
            writer.WriteBoolValue("need_volume_normalization", NeedVolumeNormalization);
            writer.WriteStringValue("text", Text);
            writer.WriteStringValue("voice_id", VoiceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
